import { freezeCanonRosterPart } from './canonRosterPackFactory.js';
const r=(key,universe,referenceUrl,heroes,enemies,bosses,worldBoss,gear,stages,x={})=>({key:key.replaceAll('-','_'),universe,aliases:[],continuity:universe,adaptationRule:'Adaptation originale fidele au canon.',visualAnchor:`silhouettes et decors de ${universe}`,referenceUrl,heroes,enemies,bosses,worldBoss,gear,stages,event:`${universe} Event`,...x});
const t=(name,objective)=>({name,nonCombat:true,objective});
const rows=[
r('interstellar-marines','Interstellar Marines','https://store.steampowered.com/app/236370/Interstellar_Marines/',['Marine Rifleman - armure ITO','Marine Medic - soutien','Marine Recon - capteurs'],['CTR Rifle Unit','CTR Heavy Unit','Defective CTR'],['Sentry Grid Evaluation','NeuroGen Incident','Starcrown Assault'],'SARA Final Evaluation',['ITO Tactical Helmet','Tactical Flashlight','Tactical Laser'],['The Vault Target Course','Blackout Infiltration','Dynamic Weather Extraction'],{aliases:['Interstellar Marine'],continuity:'Early Access publiee dans The Vault ; concepts non sortis exclus.',adaptationRule:'Marines = avatars de fonction ; missions = evaluations.',visualAnchor:'armures ITO, HUD, alarmes et meteo artificielle'}),
r('jet-set-radio','Jet Set Radio','https://store.steampowered.com/app/205950/Jet_Set_Radio/',['Beat - casque vert','Gum - tenue verte','Corn - bonnet et veste'],['Rokkaku Patrol','Rokkaku Riot Unit','Rokkaku Helicopter'],['Poison Jam','Noise Tanks','Love Shockers'],'Goji Rokkaku',['Inline Skates','Spray Can','Pirate Radio'],[t('Shibuya-cho Tag Rush','taguer les murs'),t('Benten-cho Grind Line','finir sans chute'),t('Grind Square Soul Hunt','collecter les Graffiti Souls')],{aliases:['Jet Grind Radio','JSR'],continuity:'Jeu original et reedition HD.',adaptationRule:'Rivaux de style ; stages sans combat.',visualAnchor:'cel-shading, rollers, graffiti et Tokyo-to'}),
r('killer-instinct','Killer Instinct','https://www.xbox.com/en-US/games/store/killer-instinct/BP4S3XLJG78M/0001',['Jago - epee','Orchid - tonfas','T.J. Combo - boxe'],['Ultratech Guard','Ultratech Stalker','Ultratech Drone'],['Fulgore','ARIA','Eyedol'],'Gargos',['Jago Sword','Orchid Escrima Pair','Instinct Core'],['Tiger Lair','Ultratech Industries','Astral Plane'],{aliases:['KI'],continuity:'Reboot Xbox 2013.',adaptationRule:'Aucun melange avec la chronologie arcade.',visualAnchor:'energie Instinct et technologie Ultratech'}),
r('killing-floor-2','Killing Floor 2','https://store.steampowered.com/app/232090/Killing_Floor_2/',['Mr Foster - masque a gaz','Ana Larive - punk violette','DJ Scully - DJ masque'],['Clot','Crawler','Gorefast'],['Hans Volter','King Fleshpound','Matriarch'],'Patriarch',['Trader Pod','Medical Syringe','Door Welder'],['Burning Paris','Biotics Lab','Outpost'],{aliases:['KF2'],continuity:'Killing Floor 2 uniquement.',adaptationRule:'Gore fortement attenue.',visualAnchor:'survie bio-industrielle et lumiere Horzine'}),
r('lost-planet-2','Lost Planet 2','https://store.steampowered.com/app/45750/LOST_PLANET_2/',['Snow Pirate Gunner','Jungle Pirate Scout','Ex-NEVEC Defector'],['Sepia','Genessa','Chryatis'],['Debouse','Red Eye','Gordiant'],'Over-G',['Anchor','T-ENG Harmonizer','Vital Suit'],['Jungle Pirates Route','Railway Gun Express','Over-G City'],{aliases:['LP2'],continuity:'Lost Planet 2 uniquement.',adaptationRule:'Heros = avatars de factions, aucun nom invente.',visualAnchor:'armures E.D.N. III et T-ENG orange'}),
r('magicka','Magicka','https://www.paradoxinteractive.com/games/magicka/about',['Blue Wizard - foudre','Red Wizard - feu','Yellow Wizard - froid'],['Goblin','Beastman','Undead Warrior'],['Jormungandr','Khan','Grimnir'],'Assatur',['Wizard Staff','Magick Tome','Element Wheel'],['Castle Aldrheim','Goblin Village','Havindr Arena'],{continuity:'Premier Magicka.',adaptationRule:'Magiciens = avatars colores sans biographie inventee.',visualAnchor:'robes a capuche et huit elements'}),
r('max-payne-2','Max Payne 2','https://www.rockstargames.com/games/maxpayne2',['Max Payne - Bullet Time','Mona Sax - sniper','Jim Bravura - enquete'],['Cleaner','Commando','Cleaner Sniper'],['Kaufman','Valerie Winterson','Vlad Inner Circle'],'Vladimir Lem',['Painkillers','Dual Pistols','Mona Sniper Rifle'],['Hospital Noir','Address Unknown Funhouse','Woden Manor Construction'],{aliases:['The Fall of Max Payne'],continuity:'Jeu original uniquement.',adaptationRule:'Illustre sans likeness des acteurs.',visualAnchor:'polar sous pluie et comic panels'}),
r('metal-slug','Metal Slug','https://www.snk-corp.co.jp/official/akeakaneogeo/metalslug/',['Marco Rossi','Tarma Roving','Eri Kasamoto'],['Rebel Rifleman','Rebel Bazooka Soldier','Shield Soldier'],['Allen O Neil','Iron Nokana','Big Shiee'],'General Morden - Hi-Do',['Heavy Machine Gun','Flame Shot','SV-001 Metal Slug'],['Desert Rebel Front','Occupied City','Final Mission Airfield'],{continuity:'Anthologie arcade SNK explicite.',adaptationRule:'Pixel-art caricatural, jamais photorealiste.',visualAnchor:'pixel-art et vehicules arrondis'}),
r('mirrors-edge','Mirror\'s Edge','https://www.ea.com/en/games/mirrors-edge/mirrors-edge',['Faith Connors - gant rouge','Celeste - Runner sombre','Kate Connors - soutien'],['CPF Officer','Pursuit Cop','CPF Sniper'],['Ropeburn','Celeste - Rival Runner','Jacknife'],'Callaghan Surveillance Grid',['Runner Bag','Merc Earpiece','Faith Red Glove'],[t('Rooftop Time Trial','franchir les checkpoints'),t('Runner Bag Delivery','livrer trois sacs'),t('The Shard Route Puzzle','ouvrir la route verticale')],{aliases:['Mirrors Edge'],continuity:'Jeu original de 2008.',adaptationRule:'Aucun element de Catalyst ; stages sans combat.',visualAnchor:'ville blanche et Runner Vision rouge'}),
r('oddworld','Oddworld','https://www.oddworld.com/oddworldgames/',['Abe - possession','Munch - telecommande','Stranger - Live Ammo'],['Slig','Slog','Intern'],['General Dripik','Brewmaster','Sekto'],'Molluck the Glukkon',['Shrykull Power','SpooceShrub','Live Ammo'],['RuptureFarms Rescue','Vykkers Labs','Mongo Valley Bounty'],{continuity:'Anthologie quintologie et Stranger Wrath.',adaptationRule:'Sauvetage, possession et capture de primes.',visualAnchor:'industrie organique et machines rouillees'}),
r('overgrowth','Overgrowth','https://www.wolfire.com/games/',['Turner - lapin brun','Sky - lapine grise','Sun - lapine doree'],['Catcher','Rat Slaver','Cat Guard'],['Willow','King Hickory','Ash'],'Amethyst',['Quarterstaff','Short Sword','Throwing Knife'],['White Flags Village','Rabbits of the Moon','Sky Island Fortress'],{continuity:'Campagnes Overgrowth et Lugaru, melange explicite.',adaptationRule:'Aucun personnage de mod.',visualAnchor:'animaux anthropomorphes et iles rocheuses'}),
r('palworld','Palworld','https://www.palworldgame.com/',['Lamball','Cattiva','Lifmunk'],['Rayne Syndicate Thug','Free Pal Devout','PIDF Guard'],['Zoe & Grizzbolt','Lily & Lyleen','Axel & Orserk'],'Victor & Shadowbeak',['Pal Sphere','Grappling Gun','Glider'],['Windswept Hills','Rayne Syndicate Tower','Astral Mountains'],{continuity:'Jeu de base et chefs de tours du lancement.',adaptationRule:'Pals heros ; aucun humain canon invente.',visualAnchor:'Pals colores et tours futuristes'}),
r('phantasmagoria','Phantasmagoria','https://www.gog.com/en/game/phantasmagoria',['Adrienne Delaney - illustree','Harriet - illustree','Malcolm Wyrmshadow - illustre'],['Demon Shadow','Conservatory Automaton','Carnovasch Passage'],['Mirror Chamber Trial','Theater Mechanism Trial','Hidden Chapel Trial'],'Carnovasch Demon Seal',['Protective Talisman','Letter Opener','Carnovasch Book'],[t('Carnovasch Manor Search','trouver trois indices'),t('Secret Rooms Puzzle','ouvrir les passages'),t('Banishment Trial','placer les artefacts et fuir')],{aliases:['Phantasmagoria 1995'],continuity:'Premier jeu uniquement.',adaptationRule:'Trials majoritaires ; aucun acteur reconnaissable, gore ou violence sexuelle.',visualAnchor:'manoir gothique sans likeness FMV'}),
r('sam-and-max','Sam & Max','https://skunkapegames.com/samandmax/faq/',['Sam - deduction','Max - chaos','Sybil Pandemik - expertise'],['Soda Popper Clone','Stuttgart Zombie','Maimtron 9000'],['Brady Culture','Jurgen','General Skun-kaape'],'Maxthulhu',['DeSoto Adventurer','Freelance Police Badge','Max Big Gun'],['Freelance Police Office','Stuttgart Rave','Straight & Narrow'],{continuity:'Anthologie classique et Telltale explicite.',adaptationRule:'Silhouettes cartoon et enigmes absurdes.',visualAnchor:'Freelance Police et DeSoto'}),
r('postal','Postal','https://gopostal.com/',['Postal Dude - Classic','Postal Dude - Apocalypse Weekend','Postal Dude - Brain-Damaged'],['Mad Cow','Paradise Zombie','Hostile Mascot'],['Krotchy','Mad Cow Champion','Brain-Damaged Nightmare'],'Paradise Meltdown',['Shovel','Errand Clipboard','Plush Cat Prop'],['Paradise Errand Run','Apocalypse Weekend','Brain-Damaged Dreamscape'],{continuity:'Anthologie ; variantes du meme Postal Dude.',adaptationRule:'Sans celebrite reelle, stereotype protege, nudite ni gore.',visualAnchor:'trench-coat, lunettes rouges et satire cartoon'}),
r('pubg','PUBG','https://pubg.com/en',['Assault Survivor','Scout Survivor','Medic Survivor'],['Rival Survivor','Sniper Detection Marker','Vehicle Trial Ghost'],['Red Zone Drill','Airdrop Navigation','Blue Zone Rotation'],'Final Circle',['Level 3 Helmet','Pan','First Aid Kit'],[t('Training Grounds Target Range','toucher les cibles'),t('Erangel Driving Course','finir le slalom'),t('Final Circle Survival Trial','rester couvert sans attaquer')],{aliases:['PLAYERUNKNOWNS BATTLEGROUNDS'],continuity:'PUBG contemporain ; aucun personnage narratif invente.',adaptationRule:'Avatars originaux ; stages sans combat.',visualAnchor:'casque niveau 3, parachute et Blue Zone'}),
r('la-petite-histoire-de-france','La Petite Histoire de France','https://pro.m6.fr/w9/programme/2026-1/la-petite-histoire-de-france-70068585835889856',['Francois d Arc - 1430','Philippe Honore de Roche Saint-Pierre - 1695','Renata Plancher - 1810'],['Lost Royal Decree','Empty Family Purse','Tavern Rush'],['Audience Refused','Banquet Disaster','Imperial Inspection'],'La Grande Histoire',['Tavern Ledger','Royal Seal','Imperial Serving Tray'],[t('La taverne de 1430','memoriser les commandes'),t('Le salon de 1695','resoudre le protocole'),t('L auberge de 1810','associer chambres et bagages')],{aliases:['Petite histoire de France serie'],continuity:'Serie W9/M6, entree dedupliquee.',adaptationRule:'Tout non combattant ; aucun likeness des acteurs.',visualAnchor:'costumes de 1430, 1695 et 1810',allNonCombat:true}),
];
export const CANON_ROSTER_WAVE_PART_J=freezeCanonRosterPart(rows);
