import { freezeCanonRosterPart } from './canonRosterPackFactory.js';
const r=(key,universe,referenceUrl,heroes,enemies,bosses,worldBoss,gear,stages,x={})=>({key:key.replaceAll('-','_'),universe,aliases:[],continuity:universe,adaptationRule:'Adaptation originale fidele au canon.',visualAnchor:`silhouettes et decors de ${universe}`,referenceUrl,heroes,enemies,bosses,worldBoss,gear,stages,event:`${universe} Event`,...x});
const t=(name,objective)=>({name,nonCombat:true,objective});
const rows=[
r('halloween-2018','Halloween','https://www.universalpictures.com/movies/halloween',['Laurie Strode - survivante','Karen Nelson - defense','Allyson Nelson - evasion'],['Shape Stalker','Haddonfield Blackout','Mob Panic'],['Dr Sartain','Corey Cunningham','Boogeyman Ambush'],'Michael Myers',['Laurie Rifle','Strode Trap Remote','Emergency Radio'],[t('Haddonfield Escape','atteindre la maison sure'),t('Strode Compound Traps','activer les pieges dans le bon ordre'),t('Sewer Pursuit','suivre les balises sans etre repere')],{aliases:['Halloween 2018'],continuity:'Trilogie 2018, Kills et Ends uniquement.',adaptationRule:'Aucune continuity Silver Shamrock ; tension sans gore ni copie des acteurs.',visualAnchor:'Haddonfield automnal, masque blanc, combinaison sombre et lumiere orange'}),
r('red-faction','Red Faction','https://manuals.thqnordic.com/RedFactionComplete/RedFactionComplete_PS3_Manual_US.pdf',['Parker - mineur rebelle','Eos - resistance','Alec Mason - demolition'],['Ultor Guard','EDF Trooper','Marauder'],['Masako','Sopot','General Roth'],'Adam Hale',['Mining Drill','Remote Charge','Nano Rifle'],['Ultor Mine Uprising','Eos Rebellion','Terraformer Siege'],{aliases:['Red Faction franchise'],continuity:'Anthologie explicite de la franchise.',adaptationRule:'Chaque personnage garde son epoque martienne.',visualAnchor:'Mars rouge, Geo-Mod, outils miniers et structures destructibles'}),
r('remember-me','Remember Me','https://store.steampowered.com/app/228300/Remember_Me/',['Nilin - chasseuse de memoires','Edge - liaison Errorist','Bad Request - infiltration'],['Enforcer','Leaper','Seraphim'],['Kid X-Mas','Madame','Johnny Greenteeth'],'H3O',['Sensen Glove','Spammer','Memory Remix Interface'],['Neo-Paris Rooftops','La Bastille Memory Remix','Memorize Central'],{continuity:'Jeu Capcom de 2013 uniquement.',adaptationRule:'Combats Pressen et Memory Remix selon leurs fonctions canoniques.',visualAnchor:'Neo-Paris 2084, Sensen lumineux et architecture blanche usee'}),
r('repo','R.E.P.O.','https://store.steampowered.com/app/3241660/R_E_P_O/',['Orange Semibot','Blue Semibot','Green Semibot'],['Shadow Child','Upscream','Apex Predator'],['Headman','Huntsman','Reaper'],'Trudge',['C.A.R.T. Trolley','Extraction Point','Valuable Tracker'],[t('Service Station Retrieval','porter les objets sans les casser'),t('Museum Physics Sort','trier les valuables par masse'),t('Extraction Countdown','charger le quota avant la fermeture')],{aliases:['REPO','R E P O'],continuity:'Jeu Semiwork ; trois couleurs du meme Semibot, aucune classe inventee.',adaptationRule:'Physique, transport et extraction prioritaires ; stages non combattants.',visualAnchor:'petits Semibots colores, valuables fragiles et horreur sombre'}),
r('wolfenstein-machinegames','Wolfenstein','https://bethesda.net/en/game/wolfenstein',['B.J. Blazkowicz','Anya Oliwa','Set Roth'],['Regime Soldier','Supersoldat','Kampfhund'],['Rudi Jager','London Monitor','Frau Engel'],'Deathshead',['Laserkraftwerk','Dieselkraftwerk','Da at Yichud Power Suit'],['Castle Wolfenstein Escape','London Nautica','Deathshead Compound'],{aliases:['Wolfenstein MachineGames'],continuity:'Continuite MachineGames uniquement.',adaptationRule:'Iconographie nazie seulement comme faction antagoniste, jamais glorifiee.',visualAnchor:'dieselpunk uchronique, resistance Kreisau et machines blindees'}),
r('rock-of-ages','Rock of Ages','https://store.steampowered.com/app/22230/Rock_of_Ages/',['Sisyphus','Atlas','Elpenor'],['War Elephant','Siege Tower','Explosive Cow'],['Leonidas','Napoleon','War Pope'],'Cronus',['War Boulder','Ballista','Trebuchet'],[t('Greek Boulder Race','atteindre la porte avant le rival'),t('Rococo Defense Build','placer les defenses'),t('Heavenly Gate Run','eviter les obstacles celestes')],{aliases:['Rock of Ages franchise'],continuity:'Anthologie explicite de la franchise ACE Team.',adaptationRule:'Rivaux historiques caricaturaux et course de rocher non sanglante.',visualAnchor:'collage historique, peintures animees et rochers geants'}),
r('serious-sam','Serious Sam','https://www.croteam.com/about2/',['Sam Stone','Hellfire','Kenny'],['Beheaded Kamikaze','Kleer Skeleton','Gnaar'],['Khnum','Mordekai','Mental Warlock'],'Ugh-Zan III',['Minigun','Cannon','Serious Bomb'],['Karnak Sandstorm','Siberian Wasteland','Great Pyramid Assault'],{aliases:['Serious Sam franchise'],continuity:'Anthologie explicite de la franchise Croteam.',adaptationRule:'Bestiaire et heros gardent leur humour arcade et leurs jeux d origine.',visualAnchor:'arene FPS coloree, hordes extraterrestres et monuments antiques'}),
r('skullgirls','Skullgirls','https://skullgirls.com/world/',['Parasoul','Big Band','Beowulf'],['Medici Mobster','Lab Experiment','Skeletal Minion'],['Black Dahlia','Double','Valentine'],'Marie',['Living Weapon','Egret Radio','Hurting Saxophone'],['New Meridian Streets','Lab 8','Grand Cathedral'],{continuity:'Continuite du jeu Skullgirls.',adaptationRule:'Heros adultes choisis ; tenues completes, aucune sexualisation de mineur.',visualAnchor:'animation 2D jazz, New Meridian art-deco et silhouettes de combat'}),
r('the-forest','The Forest','https://store.steampowered.com/app/242760/The_Forest/',['Eric LeBlanc','Co-op Survivor A','Co-op Survivor B'],['Cannibal','Pale Cannibal','Armsy'],['Virginia Mutant','Cowman','Worm'],'Mutant Megan',['Plane Axe','Rebreather','Crafted Bow'],['Peninsula Survival','Cave Map Expedition','Sahara Lab Escape'],{aliases:['The Forest game'],continuity:'Premier The Forest uniquement ; deux heros sont avatars co-op anonymes.',adaptationRule:'Aucun enfant blesse ; Megan finale seulement comme silhouette monstrueuse abstraite ; gore attenue.',visualAnchor:'peninsule boisee, abris artisanaux, grottes et laboratoire Sahara'}),
r('spy-fox','Spy Fox','https://www.humongous.com/games/spy-fox-in-dry-cereal/',['Spy Fox','Monkey Penny','Professor Quack'],['Henchgoat','Robot Sentry','Roach Trooper'],['William the Kid','Poodles Galore','Napoleon LeRoach'],'World Fair Doomsday Device',['Spy Watch','Gadget Cufflink','Spy Car'],[t('Dry Cereal Dairy Rescue','liberer les vaches'),t('Some Assembly Required','assembler le robot espion'),t('Operation Ozone Puzzle','reparer la couche d ozone')],{aliases:['Spy Fox franchise'],continuity:'Anthologie explicite des aventures Humongous.',adaptationRule:'Tout non combattant : gadgets, infiltration et enigmes.',visualAnchor:'espionnage cartoon, smoking blanc et gadgets colores',allNonCombat:true}),
r('squirrel-with-a-gun','Squirrel with a Gun','https://squirrelwithagun.com/',['Squirrel - Pistol Build','Squirrel - SMG Build','Squirrel - Shotgun Build'],['Agent','Sniper Agent','Security Drone'],['Elite Agent','Tank','Father'],'Mother Helicopter',['Golden Acorn','Pistol','Remote-Control Car'],[t('Acorn Parkour','collecter les glands'),t('Recoil Puzzle House','utiliser le recul pour monter'),'Agent Compound Escape'],{continuity:'Jeu de Dee Dee Creations ; trois builds du meme ecureuil.',adaptationRule:'Ne pas inventer trois ecureuils ; comedie physique et armes stylisees.',visualAnchor:'ecureuil realiste stylise, banlieue lumineuse et agents en costume'}),
r('starship-troopers-1997','Starship Troopers','https://www.sonypictures.com/movies/starshiptroopers',['Johnny Rico','Dizzy Flores','Carmen Ibanez'],['Warrior Bug','Hopper Bug','Plasma Bug'],['Tanker Bug','Plasma Battery','Whiskey Outpost Swarm'],'Brain Bug',['Morita Rifle','Mobile Infantry Helmet','Tactical Nuke'],['Klendathu Drop','Whiskey Outpost Defense','Planet P Extraction'],{aliases:['Starship Trooper'],continuity:'Film Starship Troopers de 1997 uniquement.',adaptationRule:'Aucun God Bug ou personnage des suites ; violence insectoide stylisee sans gore.',visualAnchor:'Mobile Infantry grise, deserts rocheux et Arachnides du film'}),
r('superhot','SUPERHOT','https://superhotgame.com/documents/SUPERHOT-Brand-Guidelines.pdf',['Hotswitch Build','Charge Build','Recall Build'],['Red Pistol Unit','Red Shotgun Unit','Red Katana Unit'],['Dog','Nindza','Addict'],'The System',['Katana','Red Gun','System Pyramid'],[t('Red Target Sequence','toucher les cibles rouges dans l ordre'),t('Bullet Dodge Corridor','avancer seulement au bon rythme'),t('Core Routing Puzzle','relier les trois cores')],{aliases:['SUPERHOT MIND CONTROL DELETE'],continuity:'Anthologie explicite SUPERHOT et MIND CONTROL DELETE.',adaptationRule:'Builds systeme, pas trois identites inventees ; respecter la charte blanc rouge noir.',visualAnchor:'monde blanc, ennemis rouges facettes et armes noires'}),
r('the-ball','The Ball','https://store.steampowered.com/app/35460/The_Ball/',['Unnamed Archaeologist','Ball Push Configuration','Ball Pull Configuration'],['Mummy','Fireball Zombie','Oztoc Guardian'],['Giant Mummy','Stone Brute','Arena Guardian'],'Oztoc Defense Core',['The Ball','Ancient Glove','Oztoc Torch'],[t('Pehua Caverns Roll Trial','guider la Ball dans les portes'),t('Oztoc Weight Puzzle','placer les masses sur les dalles'),t('Guardian Raceway','finir le parcours sans collision')],{continuity:'Jeu The Ball de Teotl Studios uniquement.',adaptationRule:'Un heros anonyme et deux configurations de la Ball clairement etiquetees ; stages de physique non combattants.',visualAnchor:'ruines mesoamericaines souterraines, glove magnetique et sphere de pierre'}),
r('binding-of-isaac-rebirth','The Binding of Isaac: Rebirth','https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/',['Isaac','Magdalene','Cain'],['Fly','Spider','Pooter'],['Monstro','Mom Heart','Satan'],'Mega Satan',['The D6','Yum Heart','Lucky Foot'],['Basement','Depths','Dark Room'],{aliases:['The Binding of Isack'],continuity:'Rebirth et contenu disponible dans sa famille, finale Mega Satan.',adaptationRule:'Chibi symbolique, personnages vetus, aucune nudite ni violence realiste envers un enfant.',visualAnchor:'dessin enfantin sombre, salles quadrillees et objets symboliques'}),
r('the-darkness','The Darkness','https://www.xbox.com/en-US/games/store/the-darkness/c035l0ns3sqn',['Jackie Estacado','Jenny Romano - soutien','Johnny Powell - soutien'],['Franchetti Gunman','Brotherhood Cultist','Renegade Darkling'],['Paulie Franchetti','Bragg','Victor Valente'],'The Darkness',['Darkness Guns','Black Hole Power','Darkling Portal'],['New York Subway','Otherworld Trenches','Brotherhood Mansion'],{continuity:'Anthologie explicite des deux jeux The Darkness.',adaptationRule:'Jenny et Johnny restent soutiens ; horreur et tentacules sans gore.',visualAnchor:'New York nocturne, tentacules noires et lumiere urbaine jaune'}),
r('the-surge','The Surge','https://www.deck13.com/games/the-surge',['Warren','Irina Beckett','Sally - AI support'],['CREO Worker','CREO Security Guard','Lynx Robot'],['P.A.X.','Firebug','Black Cerberus'],'Rogue Process',['Lynx Rig','CREO Exo-Rig','ASTir Spectre'],['Abandoned Production','Resolve Biolabs','The Nucleus'],{continuity:'Premier The Surge uniquement.',adaptationRule:'Irina et Sally sont des soutiens canoniques ; aucun personnage de The Surge 2.',visualAnchor:'exosquelettes industriels CREO, metal jaune et complexe en ruine'}),
];
export const CANON_ROSTER_WAVE_PART_K=freezeCanonRosterPart(rows);
