import { freezeCompactCanonRosterPart } from './canonRosterPackFactory.js';
const N=name=>({id:name.toLowerCase().replace(/\W+/g,'_'),name,visualAnchor:name,nonCombat:true,objective:`Complete ${name} without combat.`});
const X=(aliases,allNonCombat=false,rule)=>({aliases,allNonCombat,...(rule?{rule}:{})});
export const CANON_ROSTER_WAVE_PART_H=freezeCompactCanonRosterPart([
['putt_putt','Putt-Putt','https://store.steampowered.com/app/294700/PuttPutt_Saves_the_Zoo/',['Putt-Putt — purple car','Pep — brown puppy','Rover — moon rover'],['Supply Sort','Moon Maze','Zoo Gate'],['Balloon Course','Birthday Delivery','Time Portal'],'Grand Parade',['Toolbox','Clue Card','Moon Map'],['Cartown','Zoo Junction','Moon Caverns'],X(['Putt Putt'],true,'Entirely non-combat inventory and navigation trials; original fan-made art only.')]
,['borderlands_2','Borderlands 2','https://borderlands.2k.com/borderlands-2/',['Maya — Phaselock','Zer0 — Decepti0n','Salvador — Gunzerking'],['Psycho','Hyperion Loader','Bullymong'],['Captain Flynt','Wilhelm','BNK-3R'],'The Warrior',['Conference Call','Bee Shield','Transfusion'],['Southern Shelf','Bloodshot Stronghold','Hero Pass'],X(['BL2'])]
,['brink','BRINK','https://bethesda.net/en/game/brink',['Resistance Medic','Resistance Engineer','Resistance Operative'],['Security Soldier','Security Turret','Security Operative'],['Heavy Squad','Defense Grid','Counterintel Cell'],'Ark Evacuation Siege',['Revive Syringe','Turret','Data Spike'],['Container City','Security Tower','Shipyard'],X(['Brink 2011'])]
,['brutal_legend','Brütal Legend','https://www.doublefine.com/games/brutal-legend',['Eddie Riggs','Ophelia','Lars Halford'],['Battle Nun','Punishing Party','War Father'],['Ormagöden','Lionwhyte','Drowned Ophelia'],'Doviculus',['Separator','Clementine','Deuce'],['Bladehenge','Sea of Black','Coil Palace'],X(['Brutal Legend'])]
,['buckshot_roulette','Buckshot Roulette','https://www.criticalreflex.com/buckshot_roulette',['Challenger — adult 20+, closed jacket','Spotter — adult 20+, utility coat','Technician — adult 20+, coveralls'],[N('Shell Reading'),N('Item Logic'),N('Dealer Algorithm')],[N('Dealer Round I'),N('Dealer Round II'),N('Double or Nothing')],N('Final Contract'),['Magnifier','Inverter','Stop Lever'],[N('Washroom Clues'),N('Target Table'),N('Probability Room')],X(['Buckshot'],false,'No self-harm, suicide, gore or living targets; armored target-board trials only; original fan-made art.')]
,['choo_choo_charles','Choo-Choo Charles','https://www.twostargames.com/',['Archivist','Paul','Sgt. Flint'],['Cultist','Mine Enforcer','Swamp Monster'],['Warren Enforcer','Prism Defense','Charles'],'Hell Charles',['Boombox','Bug Spray','Derailer'],['Rail Loop','Mines','Prism Bridge'],X(['Choo Choo Charles'])]
,['crysis','Crysis','https://www.crytek.com/games/crysis',['Nomad','Prophet','Psycho'],['KPA Soldier','KPA Nanosuit','Ceph Scout'],['General Kyong','Ceph Hunter','Ceph Warrior'],'Ceph Warship',['SCAR','TAC Cannon','Nanosuit'],['Lingshan','Alien Sphere','Carrier'],X(['Crysis 1'])]
,['cuphead','Cuphead','https://studiomdhr.com/what-kind-of-game-is-cuphead/',['Cuphead','Mugman','Ms. Chalice'],['Acorn Maker','Woodpecker','Lobster Grunt'],['Cagney Carnation','Grim Matchstick','King Dice'],'The Devil',['Peashooter','Smoke Bomb','Astral Cookie'],['Inkwell Isle','Funhouse','Devil Casino'],X(['Cuphead DLC'])]
,['daikatana','Daikatana','https://www.gog.com/en/game/daikatana',['Hiro Miyamoto','Mikiko Ebihara','Superfly Johnson'],['Robo-Rat','Greek Skeleton','Buboid'],['Medusa','King Gharroth','Kage Guardian'],'Kage Mishima',['Daikatana','Ion Blaster','Sidewinder'],['2455 Labs','Acropolis','2030 San Francisco'],X(['Daikatana 2000'])]
,['dark_souls','Dark Souls','https://en.bandainamcoent.eu/dark-souls/dark-souls',['Chosen Undead','Solaire','Siegmeyer'],['Hollow Soldier','Balder Knight','Basilisk'],['Bell Gargoyles','Ornstein and Smough','Nito'],'Gwyn',['Estus Flask','Black Knight Sword','Havel Ring'],['Undead Burg','Anor Londo','Kiln'],X(['Dark Souls 1'])]
,['dead_rising','Dead Rising','https://www.capcom.co.jp/ir/english/news/pdf/e101028d.pdf',['Frank West','Chuck Greene','Nick Ramos'],['Zombie','Special Forces','Gas Zombie'],['Adam','Carlito','Brock'],'Outbreak Horde',['Camera','Paddle Saw','Defiler'],['Willamette','Fortune City','Los Perdidos'],X(['Dead Rising franchise'])]
,['deponia','Deponia','https://www.daedalic.com/deponia',['Rufus','Goal','Bozo'],['Surveillance Sort','Compactor Timing','Conveyor Routing'],['Cletus Logic','Argus Puzzle','Ulysses Protocol'],'Demolition Countdown',['Organon Remote','Espresso Kit','Torpedo Gear'],['KuVaq','Black Market','Organon Cruiser'],X(['Deponia series'],true,'Entirely non-combat dialogue, inventory and machinery puzzles; original fan-made art only.')]
,['deus_ex','Deus Ex','https://blog.jp.square-enix.com/deusex/2017/03/23/character.html',['Adam Jensen','Faridah Malik','Alex Vega'],['Belltower Trooper','Aug Tyrant','Security Drone'],['Barrett','Fedorova','Namir'],'Zhao and Hyron',['Combat Rifle','Typhoon','Hacking Aug'],['Detroit','Hengsha','Panchaea'],X(['Human Revolution'])]
,['devil_may_cry','Devil May Cry','https://www.capcom.co.jp/ir/english/data/oar/2018/develop/dmc.html',['Dante','Nero','Lady'],['Empusa','Hell Caina','Fury'],['Phantom','Nelo Angelo','Urizen'],'Mundus',['Rebellion','Red Queen','Kalina Ann'],['Mallet Island','Fortuna','Qliphoth'],X(['DMC'])]
,['backrooms_kane','The Backrooms — Kane Pixels','https://www.youtube.com/watch?v=H4dGpz6cnHo',['A-Sync Researcher','Missing Cameraperson','Threshold Technician'],[N('Lifeform Escape'),N('Null Navigation'),N('Threshold Distortion')],[N('Pitfalls'),N('Motion Escape'),N('Threshold Collapse')],N('Complex Evacuation'),['Camcorder','Motion Sensor','Radio'],[N('Yellow Halls'),N('Pitfalls Route'),N('Threshold Lab')],X(['Kane Pixels Backrooms'],false,'Investigation and escape only; no living target or real-person likeness; original fan-made art.')]
,['evolve','Evolve','https://www.2k.com/games/evolve/',['Markov','Val','Maggie'],['Trapjaw','Reaver','Mammoth Bird'],['Goliath','Kraken','Wraith'],'Behemoth',['Lightning Gun','Medgun','Harpoons'],['Distillery','Fusion Plant','Aviary'],X(['Evolve Stage 2'])]
,['eye_divine','E.Y.E: Divine Cybermancy','https://eye.streumon-studio.com/press/press_kit.pdf',['Culter Dei Operative','The Mentor','Dutch'],['Federation Soldier','Interceptor','Deus Ex Creature'],['Federation Commander','Rimanah','Carnophage'],'Metastreumonic Force',['BOSCO Rifle','Cyber Katana','Psi Implant'],['Temple HQ','New Eden','Mars Crypt'],X(['EYE Divine Cybermancy'])]
]);
