// Historical stage IDs and enemy template names stay stable for saves and sprite catalogs.
// Explicit rosters also make the battle use the selected local boss instead of
// the universe-wide world boss from a different game or period.
export const CANON_PRIORITY_STAGES = Object.freeze({
  lightmassTrain: Object.freeze({
    id: 1,
    name: 'Lightmass Bomb Train / RAAM',
    universe: 'Gears of War',
    mode: 'RPG',
    difficulty: 'Easy',
    goldPrize: 40,
    shardPrize: 15,
    bossName: 'General RAAM',
    canonicalBossName: 'General RAAM',
    enemyRoster: Object.freeze(['Locust Drone', 'Theron Guard', 'General RAAM']),
    enemyRosterExclusive: true,
    incarnation: 'Gears of War (2006) - Lightmass Bomb train finale',
    referenceUrl: 'https://en.wikipedia.org/wiki/Gears_of_War_(video_game)',
    referenceUrls: Object.freeze(['https://en.wikipedia.org/wiki/Gears_of_War_(video_game)', 'https://www.supercheats.com/xbox360/walkthroughs/gearsofwar-walkthrough01.txt', 'https://www.supercheats.com/xbox360/walkthroughs/gearsofwar-walkthrough03.txt']),
    visualAnchor: 'The moving Lightmass Bomb train at night, linked industrial freight cars with low cover and exposed walkways. General RAAM is a huge pale Locust in dark armored plates, carrying his Troika and surrounded by Kryll. No Pendulum Wars Aspho Fields, Skorge, Kantus, Tickers or Brumak in this encounter.',
    gameplayAdaptation: 'RPG waves condense the train assault and RAAM duel. Kryll shield blocks ordinary damage; frag grenades disperse it, swarm departures expose RAAM, and lit cover protects from the swarm. ATB commands, the shared grenade supply, durations and cover positions adapt the original real-time cover shooter.',
    visualReviewStatus: 'pending'
  }),
  metropolisScarab: Object.freeze({
    id: 2,
    name: 'Metropolis / Scarab Boarding',
    universe: 'Halo',
    mode: 'Tactics',
    tacticsBattlefieldId: 'metropolis_scarab_deck',
    difficulty: 'Easy',
    goldPrize: 40,
    shardPrize: 15,
    bossName: 'Covenant Scarab Mech',
    canonicalBossName: 'Protos-pattern Scarab',
    enemyRoster: Object.freeze(['Covenant Grunt', 'Jackal Sniper', 'Elite Minor', 'Covenant Scarab Mech']),
    enemyRosterExclusive: true,
    incarnation: 'Halo 2 (2004) - Metropolis, New Mombasa',
    referenceUrl: 'https://www.halopedia.org/Metropolis',
    referenceUrls: Object.freeze(['https://www.halopedia.org/Metropolis', 'https://www.halopedia.org/Protos-pattern_Scarab']),
    visualAnchor: 'New Mombasa streets, concrete canals and elevated building catwalks around the Halo 2 Protos-pattern Scarab. Huge four-legged purple-gray Covenant walker, flat upper deck, arched gangway, passenger cabin and forward ultra-heavy focus cannon. No Halo ring, Halo 3 Deutoros exposed rear core, Prometheans, Flood or hostile Guilty Spark.',
    gameplayAdaptation: 'Board the Halo 2 Scarab through the catwalk and neutralize its Grunt and Elite crew. The Protos hull is invulnerable; its HP and the approach sniper are not victory targets. The turn-based grid, fixed walker, route and crew count adapt Metropolis; no Halo 3 rear core is used.',
    visualReviewStatus: 'pending'
  }),
  hadleysQueen: Object.freeze({
    id: 3,
    name: "Hadley's Hope / Atmosphere Processor Hive",
    // The historical Alien key remains stable for saves and enemy sprite paths.
    universe: 'Alien',
    mode: 'Smash',
    smashArenaId: 'hadleys_processor_hive',
    difficulty: 'Easy',
    goldPrize: 45,
    shardPrize: 15,
    bossName: 'Alien Queen',
    canonicalBossName: 'Alien Queen',
    enemyRoster: Object.freeze(['Warrior Xenomorph', 'Skittering Facehugger', 'Egg Chamber Sac', 'Alien Queen']),
    enemyRosterExclusive: true,
    incarnation: "Aliens (1986) - Hadley's Hope atmosphere processor, LV-426",
    referenceUrl: 'https://en.wikipedia.org/wiki/Aliens_(film)',
    referenceUrls: Object.freeze(['https://en.wikipedia.org/wiki/Aliens_(film)', 'https://imsdb.com/scripts/Aliens.html']),
    visualAnchor: 'The LV-426 atmosphere processor near Hadley\'s Hope: industrial grated walkways overtaken by dark biomechanical resin, eggs and the Queen\'s nest. The Queen has a broad crown-like cranial crest, two large arms and two small chest arms, digitigrade legs and a long tail. Warrior Xenomorphs have ridged heads. No Predalien, dog Runner, Ash, Praetorian or Sulaco power-loader bay in this location.',
    gameplayAdaptation: 'A boss-defeat wave represents the hive confrontation; the film rescues Newt and escapes the processor, then defeats the Queen aboard the Sulaco. That rescue, evacuation and later power-loader duel remain separate unimplemented mechanics.',
    visualReviewStatus: 'pending'
  }),
  xenNihilanth: Object.freeze({
    id: 10,
    name: 'Xen / Nihilanth Chamber',
    universe: 'Half-Life',
    mode: 'Smash',
    smashArenaId: 'xen_nihilanth_chamber',
    difficulty: 'Medium',
    goldPrize: 75,
    shardPrize: 25,
    bossName: 'Alien Nihilanth Core',
    canonicalBossName: 'Nihilanth',
    enemyRoster: Object.freeze(['Vortigaunt Shock Trooper', 'Alien Nihilanth Core']),
    enemyRosterExclusive: true,
    incarnation: 'Half-Life (1998) - Xen, Nihilanth finale',
    referenceUrl: 'https://combineoverwiki.net/wiki/Nihilanth',
    referenceUrls: Object.freeze(['https://combineoverwiki.net/wiki/Nihilanth', 'https://github.com/ValveSoftware/halflife/blob/0fc8913c542d6ba129ca8bede1505e7d2e8b4b4b/dlls/nihilanth.cpp']),
    visualAnchor: 'Nihilanth\'s vast organic rock cavern on Xen, with suspended ledges and three healing crystals. A massive levitating creature with a huge head, undersized legs, two main arms and a vestigial third chest arm; orange energy spheres orbit its head, purple projectiles and green teleport spheres. Its crown opens to reveal the brain weak point. Enslaved Vortigaunts wear shackles. No Black Mesa test chamber, Strider, Combine soldier, Advisor, Antlion or Race X.',
    gameplayAdaptation: 'Destroy three healing crystals, weaken the boss and its replenishable reserve of twenty orange spheres, and hit the brain after the head opens. Body hits cannot kill Nihilanth. Platforms, crystal HP, healing intervals and purple projectile timing adapt the source encounter to Smash; green teleport spheres, teleport rooms and summoned reinforcements remain unimplemented.',
    visualReviewStatus: 'pending'
  }),
  shadowMoses: Object.freeze({
    id: 12,
    name: 'Shadow Moses REX Hangar',
    universe: 'Metal Gear',
    mode: 'Tactics',
    tacticsBattlefieldId: 'shadow_moses_rex_hangar',
    difficulty: 'Hard',
    goldPrize: 90,
    shardPrize: 30,
    bossName: 'Metal Gear REX Shadow',
    canonicalBossName: 'Metal Gear REX',
    enemyRoster: Object.freeze(['Genome Soldier Patrol', 'Metal Gear REX Shadow']),
    enemyRosterExclusive: true,
    incarnation: 'Metal Gear Solid (1998) - Shadow Moses',
    referenceUrl: 'https://www.konami.com/mg/history/us/en/',
    visualAnchor: 'Shadow Moses underground REX hangar, gray bipedal Metal Gear REX with railgun and radome, industrial gantries and Genome Soldiers. No Arsenal Gear, RAY, Gekko or FROG troops from later games.',
    visualReviewStatus: 'pending'
  }),
  legatesCamp: Object.freeze({
    id: 22,
    name: 'Hoover Dam / Legate Camp Breach',
    universe: 'Fallout',
    mode: 'Smash',
    difficulty: 'Very Hard',
    goldPrize: 170,
    shardPrize: 50,
    bossName: 'Legate Lanius General',
    canonicalBossName: 'Legate Lanius',
    enemyRoster: Object.freeze(['Legate Lanius General']),
    enemyRosterExclusive: true,
    incarnation: 'Fallout: New Vegas (2010) - Second Battle of Hoover Dam',
    referenceUrl: 'https://fallout.fandom.com/wiki/Legate_Lanius',
    visualAnchor: 'Legate Lanius at the Legate camp east of Hoover Dam, wearing his steel face mask and Legion armor with the Blade of the East. Desert cliffs, tents and palisades; no Liberty Prime or New Vegas Strip casino arena.',
    gameplayAdaptation: 'Breach residue fills regular enemy waves; Lanius is the source-locked duel opponent.',
    visualReviewStatus: 'pending'
  })
});
