import { getOcBoosterContentUpdate } from './ocBoosterContentUpdates.js';
import { ORIGINAL_WORLD_BOOSTERS as BASE_ORIGINAL_WORLD_BOOSTERS } from './originalUniverseWave.js';

const makeContentUpdateMetadata = (update) => Object.freeze({
  id: update.id,
  waveId: update.waveId,
  version: update.version,
  releasedAt: update.releasedAt,
  summary: update.summary,
  newCardIds: update.newCardIds,
  chaseRewardId: update.chaseRewardId || null
});

export const ORIGINAL_WORLD_BOOSTERS = Object.freeze(
  BASE_ORIGINAL_WORLD_BOOSTERS.map(pack => Object.freeze({
    ...pack,
    contentUpdate: makeContentUpdateMetadata(getOcBoosterContentUpdate(pack.id))
  }))
);

export const BOOSTER_ART_BY_UNIVERSE = {
  "28 Days Later": "/boosters/28-days-later.webp",
  "A Nightmare on Elm Street": "/boosters/a-nightmare-on-elm-street.webp",
  "Absolver: Downfall": "/boosters/absolver-downfall.webp",
  "Ado": "/boosters/ado.webp",
  "Adoprixtoxis": "/boosters/adoprixtoxis.webp",
  "Aegea: War of the Moirai": "/boosters/original-worlds/v2/aegea_moirai.png",
  "Aetherion: Seven Laws of Magic": "/boosters/original-worlds/v2/aetherion_seven_laws.png",
  "Aevum Fracture": "/boosters/original-worlds/v2/aevum_fracture.png",
  "Agony": "/boosters/agony.webp",
  "Alien": "/boosters/alien.webp",
  "Alien 3": "/boosters/alien-3.webp",
  "Alien Resurrection": "/boosters/alien-resurrection.webp",
  "Alien vs Predator": "/boosters/alien-vs-predator.webp",
  "Alien: Covenant": "/boosters/alien-covenant.webp",
  "Alien: Romulus": "/boosters/alien-romulus.webp",
  "Aliens": "/boosters/aliens.webp",
  "Aliens vs Predator: Requiem": "/boosters/aliens-vs-predator-requiem.webp",
  "Altered Beast": "/boosters/altered-beast.webp",
  "American Dad": "/boosters/american-dad.webp",
  "Angels Fall First": "/boosters/angels-fall-first.webp",
  "Another": "/boosters/another.webp",
  "Ash vs Evil Dead": "/boosters/ash-vs-evil-dead.webp",
  "ASMRZ": "/boosters/asmrz.webp",
  "Assassin's Creed": "/boosters/assassins-creed.webp",
  "Asterix & Obelix": "/boosters/asterix-and-obelix.webp",
  "Atarashii Gakko": "/boosters/atarashii-gakko.webp",
  "Atomic Heart": "/boosters/atomic-heart.webp",
  "Attack on Titan": "/boosters/attack-on-titan.webp",
  "Aural Vampire": "/boosters/aural-vampire.webp",
  "Avatar (Na'vi)": "/boosters/avatar-navi.webp",
  "Baby Cart": "/boosters/baby-cart.webp",
  "Babymetal": "/boosters/babymetal.webp",
  "Back to the Future": "/boosters/back-to-the-future.webp",
  "Band-Maid": "/boosters/band-maid.webp",
  "Banlieue 13": "/boosters/banlieue-13.webp",
  "Battle Royale": "/boosters/battle-royale.webp",
  "Beat Banger — Safe Rhythm Studio": "/boosters/beat-banger-safe-rhythm-studio.webp",
  "Bella Poarch": "/boosters/bella-poarch.webp",
  "Ben 10": "/boosters/ben-10.webp",
  "Bendy and the Ink Machine": "/boosters/bendy-and-the-ink-machine.webp",
  "Beyond Good & Evil": "/boosters/beyond-good-and-evil.webp",
  "Bible Black": "/boosters/bible-black.webp",
  "Big Mouth": "/boosters/big-mouth.webp",
  "Bigflo & Oli": "/boosters/bigflo-and-oli.webp",
  "Billie Eilish": "/boosters/billie-eilish.webp",
  "BioShock": "/boosters/bioshock.webp",
  "BIT.TRIP": "/boosters/bit-trip.webp",
  "Black Eyed Peas": "/boosters/black-eyed-peas.webp",
  "Blackpink": "/boosters/blackpink.webp",
  "Blade Runner": "/boosters/blade-runner.webp",
  "BlazBlue": "/boosters/blazblue.webp",
  "Borderlands": "/boosters/borderlands.webp",
  "Borderlands 2": "/boosters/borderlands-2.webp",
  "Boruto: Naruto Next Generations": "/boosters/boruto-naruto-next-generations.webp",
  "Boruto: Two Blue Vortex": "/boosters/boruto-two-blue-vortex.webp",
  "Breaking Bad": "/boosters/breaking-bad.webp",
  "Bring Me the Horizon": "/boosters/bring-me-the-horizon.webp",
  "BRINK": "/boosters/brink.webp",
  "Brütal Legend": "/boosters/brutal-legend.webp",
  "Buckethead": "/boosters/buckethead.webp",
  "Buckshot Roulette": "/boosters/buckshot-roulette.webp",
  "Buffy the Vampire Slayer": "/boosters/buffy-the-vampire-slayer.webp",
  "Camera Cafe": "/boosters/camera-cafe.webp",
  "Cells at Work!": "/boosters/cells-at-work.webp",
  "Chainsaw Man": "/boosters/chainsaw-man.webp",
  "Chappie": "/boosters/chappie.webp",
  "Charmed": "/boosters/charmed.webp",
  "Chicken Run": "/boosters/chicken-run.webp",
  "Choo-Choo Charles": "/boosters/choo-choo-charles.webp",
  "Chucky": "/boosters/chucky.webp",
  "Cloverfield": "/boosters/cloverfield.webp",
  "Commando": "/boosters/commando.webp",
  "Cool Spot": "/boosters/cool-spot.webp",
  "Counter-Strike": "/boosters/counter-strike.webp",
  "Cowboy Bebop": "/boosters/cowboy-bebop.webp",
  "Crash Bandicoot": "/boosters/crash-bandicoot.webp",
  "Croc": "/boosters/croc.webp",
  "Croc: Legend of the Gobbos": "/boosters/croc-legend-of-the-gobbos.webp",
  "Crypt of the NecroDancer": "/boosters/crypt-of-the-necrodancer.webp",
  "Crysis": "/boosters/crysis.webp",
  "Cthulhu": "/boosters/cthulhu.webp",
  "Cuphead": "/boosters/cuphead.webp",
  "Cyberpunk": "/boosters/cyberpunk.webp",
  "Cyberpunk: Edgerunners": "/boosters/cyberpunk-edgerunners.webp",
  "Daft Punk": "/boosters/daft-punk.webp",
  "Daikatana": "/boosters/daikatana.webp",
  "Dandadan": "/boosters/dandadan.webp",
  "Dante's Inferno": "/boosters/dantes-inferno.webp",
  "Dark Souls": "/boosters/dark-souls.webp",
  "Day of the Dead": "/boosters/day-of-the-dead.webp",
  "Dead by Daylight": "/boosters/dead-by-daylight.webp",
  "Dead Rising": "/boosters/dead-rising.webp",
  "Dead Space": "/boosters/dead-space.webp",
  "Deadman Wonderland": "/boosters/deadman-wonderland.webp",
  "Deadmau5": "/boosters/deadmau5.webp",
  "Death Note": "/boosters/death-note.webp",
  "Defiance": "/boosters/defiance.webp",
  "Demon Slayer": "/boosters/demon-slayer.webp",
  "Deponia": "/boosters/deponia.webp",
  "Despicer": "/boosters/despicer.webp",
  "Deus Ex": "/boosters/deus-ex.webp",
  "Devil May Cry": "/boosters/devil-may-cry.webp",
  "Devilman": "/boosters/devilman.webp",
  "Die Antwoord": "/boosters/die-antwoord.webp",
  "Digimon": "/boosters/digimon.webp",
  "Digimon Celestial Rift": "/boosters/digimon-celestial-rift.webp",
  "Digital Circus": "/boosters/digital-circus.webp",
  "Dino Crisis": "/boosters/dino-crisis.webp",
  "Discipline: The Record of a Crusade": "/boosters/discipline-the-record-of-a-crusade.webp",
  "Discworld": "/boosters/discworld.webp",
  "Disenchantment": "/boosters/disenchantment.webp",
  "Doom": "/boosters/doom.webp",
  "Doom Sweeper — Safe Apocalypse": "/boosters/doom-sweeper-safe-apocalypse.webp",
  "Dragon Ball Z": "/boosters/dragon-ball-z.webp",
  "Duke Nukem": "/boosters/duke-nukem.webp",
  "Dungeon Meshi": "/boosters/dungeon-meshi.webp",
  "Dynamite Duke": "/boosters/dynamite-duke.webp",
  "E.Y.E: Divine Cybermancy": "/boosters/e-y-e-divine-cybermancy.webp",
  "Early Edition": "/boosters/early-edition.webp",
  "Earthworm Jim": "/boosters/earthworm-jim.webp",
  "Ecco the Dolphin": "/boosters/ecco-the-dolphin.webp",
  "Elfen Lied": "/boosters/elfen-lied.webp",
  "Elvira": "/boosters/elvira.webp",
  "Eminem": "/boosters/eminem.webp",
  "Evil Dead": "/boosters/evil-dead.webp",
  "Evil Dead (2013)": "/boosters/evil-dead-2013.webp",
  "Evolution": "/boosters/evolution.webp",
  "Evolution: The Animated Series": "/boosters/evolution-the-animated-series.webp",
  "Evolve": "/boosters/evolve.webp",
  "Exit 8": "/boosters/exit-8.webp",
  "Extreme Ghostbusters": "/boosters/extreme-ghostbusters.webp",
  "F.E.A.R.": "/boosters/f-e-a-r.webp",
  "Fallout": "/boosters/fallout.webp",
  "Famille Pirate": "/boosters/famille-pirate.webp",
  "Family Guy": "/boosters/family-guy.webp",
  "Fantomas": "/boosters/fantomas.webp",
  "Final Fantasy VII": "/boosters/final-fantasy-vii.webp",
  "Final Fantasy VIII": "/boosters/final-fantasy-viii.webp",
  "Final Fantasy XIII": "/boosters/final-fantasy-xiii.webp",
  "Final Fantasy XV": "/boosters/final-fantasy-xv.webp",
  "Finding Frankie": "/boosters/finding-frankie.webp",
  "Flashback": "/boosters/flashback.webp",
  "Freddi Fish": "/boosters/freddi-fish.webp",
  "Friday the 13th": "/boosters/friday-the-13th.webp",
  "Frieren: Beyond Journeys End": "/boosters/frieren-beyond-journeys-end.webp",
  "From": "/boosters/from.webp",
  "Fullmetal Alchemist": "/boosters/fullmetal-alchemist.webp",
  "Futurama": "/boosters/futurama.webp",
  "Gantz": "/boosters/gantz.webp",
  "Gears of War": "/boosters/gears-of-war.webp",
  "Gex": "/boosters/gex.webp",
  "Ghost": "/boosters/ghost.webp",
  "Ghost in the Shell": "/boosters/ghost-in-the-shell.webp",
  "Ghostbusters": "/boosters/ghostbusters.webp",
  "Ghosts of Mars": "/boosters/ghosts-of-mars.webp",
  "Goat Simulator": "/boosters/goat-simulator.webp",
  "Godzilla": "/boosters/godzilla.webp",
  "Godzilla The Animated Series": "/boosters/godzilla-the-animated-series.webp",
  "Goemon's Great Adventure": "/boosters/goemons-great-adventure.webp",
  "Gorillaz": "/boosters/gorillaz.webp",
  "Gremlins": "/boosters/gremlins.webp",
  "GTFO": "/boosters/gtfo.webp",
  "Guilty Gear": "/boosters/guilty-gear.webp",
  "Guitar Hero": "/boosters/guitar-hero.webp",
  "Gunnm": "/boosters/gunnm.webp",
  "Guns N Roses": "/boosters/guns-n-roses.webp",
  "Gushing over Magical Girls — Safe Adult Reinterpretation": "/boosters/gushing-over-magical-girls-safe-adult-reinterpretation.webp",
  "H2G2": "/boosters/h2g2.webp",
  "Half-Life": "/boosters/half-life.webp",
  "Halloween": "/boosters/halloween.webp",
  "Halo": "/boosters/halo.webp",
  "Happy Wheels": "/boosters/happy-wheels.webp",
  "Harry Potter": "/boosters/harry-potter.webp",
  "HAWKEN": "/boosters/hawken.webp",
  "Haydee — Safe Adaptation": "/boosters/haydee-safe-adaptation.webp",
  "Hazbin Hotel": "/boosters/hazbin-hotel.webp",
  "Heart Eyes": "/boosters/heart-eyes.webp",
  "Heart of Darkness": "/boosters/heart-of-darkness.webp",
  "Heavy Metal 2000": "/boosters/heavy-metal-2000.webp",
  "Helios 56": "/boosters/original-worlds/v2/helios_56.png",
  "Hell House LLC": "/boosters/hell-house-llc.webp",
  "Hellblade: Senua’s Sacrifice": "/boosters/hellblade-senuas-sacrifice.webp",
  "Hello Neighbor": "/boosters/hello-neighbor.webp",
  "Hellraiser": "/boosters/hellraiser.webp",
  "Helluva Boss": "/boosters/helluva-boss.webp",
  "Hexen": "/boosters/hexen.webp",
  "HITMAN — World of Assassination": "/boosters/hitman-world-of-assassination.webp",
  "Home Alone": "/boosters/home-alone.webp",
  "Horizon Zero Dawn": "/boosters/horizon-zero-dawn.webp",
  "Hoshi": "/boosters/hoshi.webp",
  "Hotline Miami": "/boosters/hotline-miami.webp",
  "House of 1000 Corpses": "/boosters/house-of-1000-corpses.webp",
  "House of the Dead": "/boosters/house-of-the-dead.webp",
  "House of the Dead 2": "/boosters/house-of-the-dead-2.webp",
  "House of the Dead 3": "/boosters/house-of-the-dead-3.webp",
  "How to Make a Monster": "/boosters/how-to-make-a-monster.webp",
  "Ice Age": "/boosters/ice-age.webp",
  "Ilyr Concordat": "/boosters/original-worlds/v2/ilyr_concordat.png",
  "Imperium Aeternum": "/boosters/original-worlds/v2/imperium_aeternum.png",
  "Indila": "/boosters/indila.webp",
  "Infernum: Nine Pits": "/boosters/original-worlds/v2/infernum_nine_pits.png",
  "Inside Out": "/boosters/inside-out.webp",
  "Insidious": "/boosters/insidious.webp",
  "Interstellar Marines": "/boosters/interstellar-marines.webp",
  "Inuyashiki": "/boosters/inuyashiki.webp",
  "Invincible": "/boosters/invincible.webp",
  "Iron Sky": "/boosters/iron-sky.webp",
  "Iron Tempest": "/boosters/original-worlds/v2/iron_tempest.png",
  "Italian Brainrot": "/boosters/italian-brainrot.webp",
  "Jersey Devil": "/boosters/jersey-devil.webp",
  "Jet Set Radio": "/boosters/jet-set-radio.webp",
  "John Wick": "/boosters/john-wick.webp",
  "JoJo's Bizarre Adventure": "/boosters/jojos-bizarre-adventure.webp",
  "Joker New 52": "/boosters/joker-new-52.webp",
  "Kaamelott": "/boosters/kaamelott.webp",
  "Karune Cal": "/boosters/karune-cal.webp",
  "Kazaam": "/boosters/kazaam.webp",
  "Kemet: The Devoured Sun": "/boosters/original-worlds/v2/kemet_devoured_sun.png",
  "Kill Bill": "/boosters/kill-bill.webp",
  "Killer Instinct": "/boosters/killer-instinct.webp",
  "Killer Tomatoes from Outer Space": "/boosters/killer-tomatoes-from-outer-space.webp",
  "Killing Floor 2": "/boosters/killing-floor-2.webp",
  "Killzone": "/boosters/killzone.webp",
  "Korn": "/boosters/korn.webp",
  "Kung Pow": "/boosters/kung-pow.webp",
  "Kyary Pamyu Pamyu": "/boosters/kyary-pamyu-pamyu.webp",
  "La Casa de Papel": "/boosters/la-casa-de-papel.webp",
  "La Cite de la Peur": "/boosters/la-cite-de-la-peur.webp",
  "La Petite Histoire de France": "/boosters/la-petite-histoire-de-france.webp",
  "Lady Gaga": "/boosters/lady-gaga.webp",
  "Ladybaby": "/boosters/ladybaby.webp",
  "Land of the Dead": "/boosters/land-of-the-dead.webp",
  "Last Action Hero": "/boosters/last-action-hero.webp",
  "Le Cinquième Element": "/boosters/le-cinquieme-element.webp",
  "Le Donjon de Naheulbeuk": "/boosters/donjon-de-naheulbeuk.webp",
  "Left 4 Dead": "/boosters/left-4-dead.webp",
  "Legacy of Kain": "/boosters/legacy-of-kain.webp",
  "Les Aventures de Saturnin": "/boosters/les-aventures-de-saturnin.webp",
  "Les Aventuriers du Survivaure": "/boosters/aventuriers-du-survivaure.webp",
  "Les Chevaliers du Fiel": "/boosters/les-chevaliers-du-fiel.webp",
  "Les Inconnus": "/boosters/les-inconnus.webp",
  "Les Kassos": "/boosters/les-kassos.webp",
  "Les Tuche": "/boosters/les-tuche.webp",
  "Les Visiteurs": "/boosters/les-visiteurs.webp",
  "Les Visiteurs du Futur": "/boosters/les-visiteurs-du-futur.webp",
  "Les Zinzins de l’espace": "/boosters/les-zinzins-de-lespace.webp",
  "Like a Dragon": "/boosters/like-a-dragon.webp",
  "Lil Nas X": "/boosters/lil-nas-x.webp",
  "Lilo & Stitch": "/boosters/lilo-and-stitch.webp",
  "Linkin Park": "/boosters/linkin-park.webp",
  "Little Big": "/boosters/little-big.webp",
  "LittleBigPlanet": "/boosters/littlebigplanet.webp",
  "Lost Planet 2": "/boosters/lost-planet-2.webp",
  "M3GAN": "/boosters/m3gan.webp",
  "Mad Max": "/boosters/mad-max.webp",
  "Mad Max: Fury Road": "/boosters/mad-max-fury-road.webp",
  "MagiC JacK": "/boosters/magic-jack.webp",
  "Magicka": "/boosters/magicka.webp",
  "Malcolm in the Middle": "/boosters/malcolm-in-the-middle.webp",
  "Man with a Mission": "/boosters/man-with-a-mission.webp",
  "Mandate of Nine Heavens": "/boosters/original-worlds/v2/mandate_nine_heavens.png",
  "Marathon": "/boosters/marathon.webp",
  "Marble Hornets": "/boosters/marble-hornets.webp",
  "Marilyn Manson": "/boosters/marilyn-manson.webp",
  "Mars Attacks": "/boosters/mars-attacks.webp",
  "Marvel Zombies — MCU Animation": "/boosters/marvel-zombies-mcu-animation.webp",
  "Mashle": "/boosters/mashle.webp",
  "Mass Effect": "/boosters/mass-effect.webp",
  "Max Payne 2": "/boosters/max-payne-2.webp",
  "MDK": "/boosters/mdk.webp",
  "MediEvil": "/boosters/medievil.webp",
  "Meet the Feebles": "/boosters/meet-the-feebles.webp",
  "Men in Black": "/boosters/men-in-black.webp",
  "Meridian Clockwork": "/boosters/original-worlds/v2/meridian_clockwork.png",
  "Méridien Creux": "/boosters/meridien-creux.webp",
  "Metal Gear": "/boosters/metal-gear.webp",
  "Metal Gear Rising": "/boosters/metal-gear-rising.webp",
  "Metal Slug": "/boosters/metal-slug.webp",
  "Metal: Hellsinger": "/boosters/metal-hellsinger.webp",
  "Michael Jackson": "/boosters/michael-jackson.webp",
  "Minecraft": "/boosters/minecraft.webp",
  "Minions": "/boosters/minions.webp",
  "Mirror's Edge": "/boosters/mirrors-edge.webp",
  "Moonwalker": "/boosters/moonwalker.webp",
  "Mr. Bean": "/boosters/mr-bean.webp",
  "Murder Drones": "/boosters/murder-drones.webp",
  "Mythos Primordia": "/boosters/original-worlds/v2/mythos_primordia.png",
  "Naruto": "/boosters/naruto.webp",
  "Naruto Shippuden": "/boosters/naruto-shippuden.webp",
  "Natural Selection 2": "/boosters/natural-selection-2.webp",
  "Necronomicon": "/boosters/necronomicon.webp",
  "Negima": "/boosters/negima.webp",
  "Nemesis — Awaken Realms": "/boosters/nemesis-awaken-realms.webp",
  "Neon Genesis Evangelion": "/boosters/neon-genesis-evangelion.webp",
  "Neon Requiem": "/boosters/original-worlds/v2/neon_requiem.png",
  "Nicolas et Pimprenelle": "/boosters/nicolas-et-pimprenelle.webp",
  "NieR": "/boosters/nier.webp",
  "Night of the Living Dead": "/boosters/night-of-the-living-dead.webp",
  "Nightwish": "/boosters/nightwish.webp",
  "Nine Realms: Last Twilight": "/boosters/original-worlds/v2/nine_realms_last_twilight.png",
  "No Man's Sky": "/boosters/no-mans-sky.webp",
  "Noelle Perna": "/boosters/noelle-perna.webp",
  "Noob": "/boosters/noob.webp",
  "Nyan Cat": "/boosters/nyan-cat.webp",
  "Oddworld": "/boosters/oddworld.webp",
  "Oggy et les Cafards": "/boosters/oggy-et-les-cafards.webp",
  "Oliver Tree": "/boosters/oliver-tree.webp",
  "One Punch Man": "/boosters/one-punch-man.webp",
  "Onechanbara": "/boosters/onechanbara.webp",
  "Overgrowth": "/boosters/overgrowth.webp",
  "Overlord Anime": "/boosters/overlord-anime.webp",
  "Palworld": "/boosters/palworld.webp",
  "Parasite Eve": "/boosters/parasite-eve.webp",
  "Parasyte": "/boosters/parasyte.webp",
  "Payday": "/boosters/payday.webp",
  "Pee-wee": "/boosters/pee-wee.webp",
  "Peepoodo — Safe Educational Adaptation": "/boosters/peepoodo-safe-educational-adaptation.webp",
  "Phantasmagoria": "/boosters/phantasmagoria.webp",
  "Pingu": "/boosters/pingu.webp",
  "Pirates of the Caribbean": "/boosters/pirates-of-the-caribbean.webp",
  "Planete Hurlante": "/boosters/planete-hurlante.webp",
  "Plants vs. Zombies": "/boosters/plants-vs-zombies.webp",
  "Police Squad": "/boosters/police-squad.webp",
  "Poppy Playtime": "/boosters/poppy-playtime.webp",
  "Portal": "/boosters/portal.webp",
  "Postal": "/boosters/postal.webp",
  "Predator": "/boosters/predator.webp",
  "Predator 2": "/boosters/predator-2.webp",
  "Predator: Badlands": "/boosters/predator-badlands.webp",
  "Predator: Killer of Killers": "/boosters/predator-killer-of-killers.webp",
  "Predators": "/boosters/predators.webp",
  "Prey": "/boosters/prey.webp",
  "Prey (2006)": "/boosters/prey-2006.webp",
  "Prometheus": "/boosters/prometheus.webp",
  "PSY": "/boosters/psy.webp",
  "Psycho-Pass": "/boosters/psycho-pass.webp",
  "PUBG": "/boosters/pubg.webp",
  "Puppet Master": "/boosters/puppet-master.webp",
  "Putt-Putt": "/boosters/putt-putt.webp",
  "Quake": "/boosters/quake.webp",
  "Queen Bee": "/boosters/queen-bee.webp",
  "R.E.P.O.": "/boosters/r-e-p-o.webp",
  "Rambo": "/boosters/rambo.webp",
  "Rammstein": "/boosters/rammstein.webp",
  "Rayman": "/boosters/rayman.webp",
  "Re-Animator": "/boosters/re-animator.webp",
  "REC": "/boosters/rec.webp",
  "Red Faction": "/boosters/red-faction.webp",
  "Redneck Rampage": "/boosters/redneck-rampage.webp",
  "Reflets d’Acide": "/boosters/reflets-d-acide.webp",
  "Remember Me": "/boosters/remember-me.webp",
  "Repo! The Genetic Opera": "/boosters/repo-the-genetic-opera.webp",
  "Resident Evil": "/boosters/resident-evil.webp",
  "Richard au pays des livres magiques": "/boosters/richard-au-pays-des-livres-magiques.webp",
  "Rick & Morty": "/boosters/rick-and-morty.webp",
  "Rick Astley": "/boosters/rick-astley.webp",
  "Ristar": "/boosters/ristar.webp",
  "Rival Schools": "/boosters/rival-schools.webp",
  "Rob Zombie": "/boosters/rob-zombie.webp",
  "RoboCop": "/boosters/robocop.webp",
  "Rock of Ages": "/boosters/rock-of-ages.webp",
  "Rocky": "/boosters/rocky.webp",
  "Rocky Horror Picture Show": "/boosters/rocky-horror-picture-show.webp",
  "Roger Rabbit": "/boosters/roger-rabbit.webp",
  "Rosario + Vampire": "/boosters/rosario-plus-vampire.webp",
  "RRRrrrr!!!": "/boosters/rrrrrrr.webp",
  "Rubber": "/boosters/rubber.webp",
  "Rugrats": "/boosters/rugrats.webp",
  "Rurouni Kenshin": "/boosters/rurouni-kenshin.webp",
  "Sam & Max": "/boosters/sam-and-max.webp",
  "Samantha Oups!": "/boosters/samantha-oups.webp",
  "Sanctum": "/boosters/sanctum.webp",
  "Sartorius Stedim Biotech": "/boosters/sartorius-stedim-biotech.webp",
  "Sausage Party": "/boosters/sausage-party.webp",
  "Saw": "/boosters/saw.webp",
  "Scary Movie": "/boosters/scary-movie.webp",
  "SCP Foundation": "/boosters/scp-foundation.webp",
  "Seaman": "/boosters/seaman.webp",
  "Secret of Monkey Island": "/boosters/secret-of-monkey-island.webp",
  "Serious Sam": "/boosters/serious-sam.webp",
  "Shadow Man": "/boosters/shadow-man.webp",
  "Shaka Ponk": "/boosters/shaka-ponk.webp",
  "Shakira": "/boosters/shakira.webp",
  "Sharknado": "/boosters/sharknado.webp",
  "Shaun of the Dead": "/boosters/shaun-of-the-dead.webp",
  "Silent Hill": "/boosters/silent-hill.webp",
  "Silent Hill f": "/boosters/silent-hill-f.webp",
  "Sinister": "/boosters/sinister.webp",
  "Siren Head": "/boosters/siren-head.webp",
  "Skibidi": "/boosters/skibidi.webp",
  "Skrillex": "/boosters/skrillex.webp",
  "Skullgirls": "/boosters/skullgirls.webp",
  "Skyline": "/boosters/skyline.webp",
  "Slender Man": "/boosters/slender-man.webp",
  "Small Soldiers": "/boosters/small-soldiers.webp",
  "Solar Opposites": "/boosters/solar-opposites.webp",
  "Soldier of Fortune": "/boosters/soldier-of-fortune.webp",
  "Solo Leveling": "/boosters/solo-leveling.webp",
  "Sonic": "/boosters/sonic.webp",
  "Soul Calibur": "/boosters/soul-calibur.webp",
  "Spawn": "/boosters/spawn.webp",
  "Spermageddon": "/boosters/spermageddon.webp",
  "Spider: The Video Game": "/boosters/spider-the-video-game.webp",
  "Splatterhouse": "/boosters/splatterhouse.webp",
  "Splice": "/boosters/splice.webp",
  "Spoof Movie": "/boosters/spoof-movie.webp",
  "Spy Fox": "/boosters/spy-fox.webp",
  "Spy Kids": "/boosters/spy-kids.webp",
  "Spy x Family": "/boosters/spy-x-family.webp",
  "Spyro": "/boosters/spyro.webp",
  "Squid Game": "/boosters/squid-game.webp",
  "Squirrel with a Gun": "/boosters/squirrel-with-a-gun.webp",
  "Stan Helsing": "/boosters/stan-helsing.webp",
  "Star Wars": "/boosters/star-wars.webp",
  "Stargate": "/boosters/stargate.webp",
  "Stargate Atlantis": "/boosters/stargate-atlantis.webp",
  "Stargate Infinity": "/boosters/stargate-infinity.webp",
  "Stargate Universe": "/boosters/stargate-universe.webp",
  "Starship Troopers": "/boosters/starship-troopers.webp",
  "Steins;Gate": "/boosters/steins-gate.webp",
  "Stellar Dream — Safe Colony Mission": "/boosters/stellar-dream-safe-colony-mission.webp",
  "Stranger Things": "/boosters/stranger-things.webp",
  "Streets of Rage": "/boosters/streets-of-rage.webp",
  "Sub Urban": "/boosters/sub-urban.webp",
  "Subverse — Safe Galactic Rebellion": "/boosters/subverse-safe-galactic-rebellion.webp",
  "Super Meat Boy": "/boosters/super-meat-boy.webp",
  "Superhero Movie": "/boosters/superhero-movie.webp",
  "SUPERHOT": "/boosters/superhot.webp",
  "Sword Art Online": "/boosters/sword-art-online.webp",
  "Sword Art Online: Gun Gale Online": "/boosters/sword-art-online-gun-gale-online.webp",
  "System of a Down": "/boosters/system-of-a-down.webp",
  "Tail Concerto": "/boosters/tail-concerto.webp",
  "Tanya the Evil": "/boosters/tanya-the-evil.webp",
  "Tawantinsuyu: The Split Sun": "/boosters/original-worlds/v2/tawantinsuyu_split_sun.png",
  "Team Fortress 2": "/boosters/team-fortress-2.webp",
  "Teen Titans": "/boosters/teen-titans.webp",
  "Tekken": "/boosters/tekken.webp",
  "Téléchat": "/boosters/telechat.webp",
  "Tenacious D": "/boosters/tenacious-d.webp",
  "Terminator": "/boosters/terminator.webp",
  "Terrifier": "/boosters/terrifier.webp",
  "Thalassa Mnémique": "/boosters/thalassa-mnemique.webp",
  "The Aether Crown": "/boosters/original-worlds/v2/aether_crown.png",
  "The Amazing Patate Show": "/boosters/the-amazing-patate-show.webp",
  "The Backrooms — Kane Pixels": "/boosters/the-backrooms-kane-pixels.webp",
  "The Ball": "/boosters/the-ball.webp",
  "The Batman Who Laughs": "/boosters/the-batman-who-laughs.webp",
  "The Big Bang Theory": "/boosters/the-big-bang-theory.webp",
  "The Binding of Isaac: Rebirth": "/boosters/the-binding-of-isaac-rebirth.webp",
  "The Brave Little Toaster": "/boosters/the-brave-little-toaster.webp",
  "The Collector": "/boosters/the-collector.webp",
  "The Conjuring": "/boosters/the-conjuring.webp",
  "The Creator": "/boosters/the-creator.webp",
  "The Crownless Sea": "/boosters/original-worlds/v2/crownless_sea.png",
  "The Da Vinci Code": "/boosters/the-da-vinci-code.webp",
  "The Dark Knight": "/boosters/the-dark-knight.webp",
  "The Darkness": "/boosters/the-darkness.webp",
  "The Drowned Testament": "/boosters/original-worlds/v2/drowned_testament.png",
  "The Expendables": "/boosters/the-expendables.webp",
  "The Forest": "/boosters/the-forest.webp",
  "The Grudge": "/boosters/the-grudge.webp",
  "The Horribly Slow Murderer": "/boosters/the-horribly-slow-murderer.webp",
  "The Last of Us": "/boosters/the-last-of-us.webp",
  "The Lord of the Rings": "/boosters/the-lord-of-the-rings.webp",
  "The Matrix": "/boosters/the-matrix.webp",
  "The Mummy": "/boosters/the-mummy.webp",
  "The Predator": "/boosters/the-predator.webp",
  "The Purge": "/boosters/the-purge.webp",
  "The Ring": "/boosters/the-ring.webp",
  "The Silence of the Lambs": "/boosters/the-silence-of-the-lambs.webp",
  "The Simpsons": "/boosters/the-simpsons.webp",
  "The Smurfs": "/boosters/the-smurfs.webp",
  "The Surge": "/boosters/the-surge.webp",
  "The Texas Chain Saw Massacre": "/boosters/the-texas-chain-saw-massacre.webp",
  "The Thing": "/boosters/the-thing.webp",
  "The Truman Show": "/boosters/the-truman-show.webp",
  "The Walking Dead — Telltale": "/boosters/the-walking-dead-telltale.webp",
  "The Weeknd": "/boosters/the-weeknd.webp",
  "The Wild Thornberrys": "/boosters/the-wild-thornberrys.webp",
  "Them!": "/boosters/them.webp",
  "Tintin": "/boosters/tintin.webp",
  "Titanfall 2": "/boosters/titanfall-2.webp",
  "Tokyo Ghoul": "/boosters/tokyo-ghoul.webp",
  "Tom Clancy’s Splinter Cell": "/boosters/tom-clancys-splinter-cell.webp",
  "Tomb Raider": "/boosters/tomb-raider.webp",
  "Tomba": "/boosters/tomba.webp",
  "Tommy Heavenly6": "/boosters/tommy-heavenly6.webp",
  "Torbahead": "/boosters/torbahead.webp",
  "Toxic Avenger": "/boosters/toxic-avenger.webp",
  "Toy Soldiers": "/boosters/toy-soldiers.webp",
  "Tremors": "/boosters/tremors.webp",
  "Trololo": "/boosters/trololo.webp",
  "Turok": "/boosters/turok.webp",
  "Twisted Metal": "/boosters/twisted-metal.webp",
  "Ultra Vomit": "/boosters/ultra-vomit.webp",
  "Universal Soldier": "/boosters/universal-soldier.webp",
  "Unreal": "/boosters/unreal.webp",
  "Unreal Tournament": "/boosters/unreal-tournament.webp",
  "Unreal Tournament 2004": "/boosters/unreal-tournament-2004.webp",
  "Uzumaki": "/boosters/uzumaki.webp",
  "Valedor: The Shattered Crown": "/boosters/original-worlds/v2/valedor_shattered_crown.png",
  "VelociPastor": "/boosters/velocipastor.webp",
  "Viridienne Ultime": "/boosters/viridienne-ultime.webp",
  "Virus": "/boosters/virus.webp",
  "Vocaloid": "/boosters/vocaloid.webp",
  "Voyage de Chihiro": "/boosters/voyage-de-chihiro.webp",
  "Wakfu": "/boosters/wakfu.webp",
  "Wallace & Gromit": "/boosters/wallace-and-gromit.webp",
  "War of the Worlds": "/boosters/war-of-the-worlds.webp",
  "Warhammer 40,000: Space Marine": "/boosters/warhammer-40-000-space-marine.webp",
  "Within Temptation": "/boosters/within-temptation.webp",
  "Wolfenstein": "/boosters/wolfenstein.webp",
  "Woodruff": "/boosters/woodruff.webp",
  "Worms": "/boosters/worms.webp",
  "Wrong Turn": "/boosters/wrong-turn.webp",
  "Yakuza": "/boosters/yakuza.webp",
  "Yomi no Kage": "/boosters/original-worlds/v2/yomi_no_kage.png",
  "Yu-Gi-Oh": "/boosters/yu-gi-oh.webp",
  "Zak et Crysta": "/boosters/zak-et-crysta.webp",
  "Zero Escape: The Nonary Games": "/boosters/zero-escape-the-nonary-games.webp",
  "Zombi": "/boosters/zombi.webp",
  "Zombies Ate My Neighbors": "/boosters/zombies-ate-my-neighbors.webp",
  "Zootopia": "/boosters/zootopia.webp",
  "Zorro": "/boosters/zorro.webp"
};

export const BOOSTER_ART_UNIVERSES = Object.freeze(Object.keys(BOOSTER_ART_BY_UNIVERSE));
export const MULTIVERSE_CONVERGENCE_BOOSTER_ART = '/boosters/multiverse-convergence.webp';
export const PERMANENT_OC_BOOSTERS = Object.freeze([
  {
    id: 'oc:keepers-of-name',
    art: '/boosters/oc-keepers-of-name.webp',
    backdrop: '/images/campaign-oc/chapter-01-atrium-v1.png',
    universe: 'Nexus de Convergence',
    mode: 'RPG',
    shape: 'omniverse',
    color: '#39c5bb',
    priceTier: 'targeted',
    mediaLabel: { fr: 'CHAPITRE I', en: 'CHAPTER I' },
    label: { fr: 'Booster Gardiens du Nom', en: 'Keepers of the Name Booster' },
    desc: {
      fr: 'Mirelle, Bastion et les protocoles qui protègent les identités.',
      en: 'Mirelle, Bastion, and the protocols that protect identities.'
    },
    meta: {
      fr: 'Pack OC permanent ciblé sur l Atrium central et le premier Verrou des Noms.',
      en: 'Permanent OC pack focused on the Central Atrium and the first Lock of Names.'
    },
    searchText: 'Nexus OC Atrium Mirelle Bastion noms balises anchor names',
    heroIds: ['arca_mirelle', 'arca_bastion'],
    rewardKinds: [
      'hero',
      'equipment',
      'event',
      'skin',
      'archive',
      'hud',
      'introPose',
      'victoryPose',
      'profileBanner',
      'profileTitle'
    ],
    chaseRewardId: 'hud:oc_lock_of_name',
    guaranteeNonHeroRare: true
  },
  {
    id: 'oc:divergent-shards',
    art: '/boosters/oc-divergent-shards.webp',
    backdrop: '/images/campaign-oc/chapter-02-origin-forge-v1.png',
    universe: 'Nexus de Convergence',
    mode: 'RPG',
    shape: 'omniverse',
    color: '#7df9ff',
    priceTier: 'targeted',
    mediaLabel: { fr: 'CHAPITRE II', en: 'CHAPTER II' },
    label: { fr: 'Booster Éclats Divergents', en: 'Divergent Shards Booster' },
    desc: {
      fr: 'Nova, Marrow et les vies possibles de la Forge d Origine.',
      en: 'Nova, Marrow, and the possible lives of the Origin Forge.'
    },
    meta: {
      fr: 'Pack OC permanent ciblé sur les doubles, les Éclats d Origine et les fractures.',
      en: 'Permanent OC pack focused on doubles, Origin Shards, and fractures.'
    },
    searchText: 'Nexus OC Nova Marrow forge origine doubles divergent shards',
    heroIds: ['arca_nova', 'arca_marrow'],
    rewardKinds: [
      'hero',
      'equipment',
      'skin',
      'archive',
      'battleMusic',
      'stageMusic',
      'fieldSuper',
      'koEffect',
      'portalEffect',
      'victoryPose'
    ],
    chaseRewardId: 'field-super:oc_incompatible_versions_verdict',
    guaranteeNonHeroRare: true
  },
  {
    id: 'oc:black-ledger',
    art: '/boosters/oc-black-ledger.webp',
    backdrop: '/images/campaign-oc/chapter-03-black-ledger-v1.png',
    universe: 'Nexus de Convergence',
    mode: 'Tactics',
    shape: 'card',
    color: '#d9b86b',
    priceTier: 'targeted',
    mediaLabel: { fr: 'CHAPITRE III', en: 'CHAPTER III' },
    label: { fr: 'Booster Registre Noir', en: 'Black Ledger Booster' },
    desc: {
      fr: 'Sable, Loom et les traces vivantes du Registre des absents.',
      en: 'Sable, Loom, and the living traces of the Ledger of the Missing.'
    },
    meta: {
      fr: 'Pack OC permanent ciblé sur les archives censurées et la dette d A.R.C.A.',
      en: 'Permanent OC pack focused on censored archives and A.R.C.A. s debt.'
    },
    searchText: 'Nexus OC Sable Loom registre noir archives ledger missing',
    heroIds: ['arca_sable', 'arca_loom'],
    rewardKinds: [
      'hero',
      'equipment',
      'event',
      'archive',
      'hud',
      'stageMusic',
      'npcAssist',
      'victoryPose',
      'profileBanner',
      'profileTitle'
    ],
    chaseRewardId: 'hud:oc_black_ledger_restored_lines',
    guaranteeNonHeroRare: true
  },
  {
    id: 'oc:impossible-exodus',
    art: '/boosters/oc-impossible-exodus.webp',
    backdrop: '/images/campaign-oc/chapter-04-broken-portal-yard-v1.png',
    universe: 'Nexus de Convergence',
    mode: 'Smash',
    shape: 'iris',
    color: '#ff8c00',
    priceTier: 'targeted',
    mediaLabel: { fr: 'CHAPITRE IV', en: 'CHAPTER IV' },
    label: { fr: 'Booster Exode Impossible', en: 'Impossible Exodus Booster' },
    desc: {
      fr: 'Bastion, Loom et la Cour des faux passages.',
      en: 'Bastion, Loom, and the Court of False Passages.'
    },
    meta: {
      fr: 'Pack OC permanent ciblé sur les portes mensongères et la seule route causale.',
      en: 'Permanent OC pack focused on lying doors and the single causal route.'
    },
    searchText: 'Nexus OC Bastion Loom exode impossible faux passages dead gates',
    heroIds: ['arca_bastion', 'arca_loom'],
    rewardKinds: [
      'hero',
      'equipment',
      'archive',
      'kart',
      'battleMusic',
      'stageMusic',
      'fieldSuper',
      'npcAssist',
      'portalEffect',
      'introPose',
      'victoryPose'
    ],
    chaseRewardId: 'portal-effect:oc_named_losses_gate',
    guaranteeNonHeroRare: true
  },
  {
    id: 'oc:last-margin',
    art: '/boosters/oc-last-margin.webp',
    backdrop: '/images/campaign-oc/chapter-05-white-threshold-v1.png',
    universe: 'Nexus de Convergence',
    mode: 'RPG',
    shape: 'omniverse',
    color: '#ff5b6e',
    priceTier: 'targeted',
    mediaLabel: { fr: 'CHAPITRE V', en: 'CHAPTER V' },
    label: { fr: 'Booster Dernière Marge', en: 'Last Margin Booster' },
    desc: {
      fr: 'Toute la Cellule ZÉRO face au Seuil du Sans-Auteur.',
      en: 'The full Cell ZERO facing the Authorless Threshold.'
    },
    meta: {
      fr: 'Pack OC permanent final réunissant les six signatures et tout l arsenal du Nexus.',
      en: 'Final permanent OC pack combining all six signatures and the full Nexus arsenal.'
    },
    searchText: 'Nexus OC Cellule ZERO Sans Auteur seuil last margin authorless',
    heroIds: [
      'arca_mirelle',
      'arca_bastion',
      'arca_nova',
      'arca_marrow',
      'arca_sable',
      'arca_loom'
    ],
    rewardKinds: null,
    chaseRewardId: 'field-super:oc_six_origin_locks_sentence',
    guaranteeNonHeroRare: true
  }
].map(pack => {
  const update = getOcBoosterContentUpdate(pack.id);
  const contentUpdate = makeContentUpdateMetadata(update);
  return Object.freeze({
    ...pack,
    heroIds: Object.freeze([...pack.heroIds]),
    rewardKinds: pack.rewardKinds ? Object.freeze([...pack.rewardKinds]) : null,
    contentUpdate
  });
}));
export const DEFAULT_OC_BOOSTER_ID = PERMANENT_OC_BOOSTERS[0].id;
export const BOOSTER_ART_BY_PACK_ID = Object.freeze({
  ...Object.fromEntries(PERMANENT_OC_BOOSTERS.map(pack => [pack.id, pack.art])),
  ...Object.fromEntries(ORIGINAL_WORLD_BOOSTERS.map(pack => [pack.id, pack.art])),
  multi: MULTIVERSE_CONVERGENCE_BOOSTER_ART
});
export const BOOSTER_ROTATION_WINDOW_MS = 24 * 60 * 60 * 1000;
export const BOOSTER_ROTATION_SIZE = 8;

export const getPortalBoosterArt = (universe) => BOOSTER_ART_BY_UNIVERSE[universe] || null;
export const getPortalBoosterPackArt = (packId) => BOOSTER_ART_BY_PACK_ID[packId] || null;

export const getPortalBoosterRotation = (
  universes = BOOSTER_ART_UNIVERSES,
  now = Date.now()
) => {
  const uniqueUniverses = [...new Set(universes)].filter(Boolean);
  const timestamp = Number.isFinite(Number(now)) ? Math.max(0, Number(now)) : 0;
  const cycle = Math.floor(timestamp / BOOSTER_ROTATION_WINDOW_MS);
  const nextRotationAt = (cycle + 1) * BOOSTER_ROTATION_WINDOW_MS;

  if (uniqueUniverses.length === 0) {
    return {
      cycle,
      universes: [],
      nextRotationAt,
      remainingMs: Math.max(0, nextRotationAt - timestamp)
    };
  }

  const featuredCount = Math.min(BOOSTER_ROTATION_SIZE, uniqueUniverses.length);
  const startIndex = (cycle * featuredCount) % uniqueUniverses.length;
  const featuredUniverses = Array.from(
    { length: featuredCount },
    (_, index) => uniqueUniverses[(startIndex + index) % uniqueUniverses.length]
  );

  return {
    cycle,
    universes: featuredUniverses,
    nextRotationAt,
    remainingMs: Math.max(0, nextRotationAt - timestamp)
  };
};
