import { SOLAR_OPPOSITES_SIREN_STAR_WARS_UNIVERSE_WAVE } from './solarOppositesSirenStarWarsPack';

// Canon-focused universe packs requested after the large expanded-universe wave.
// Keep aliases in comments so future imports do not create duplicate universes.
export const REQUESTED_UNIVERSE_WAVE = [
  {
    key: 'chainsaw_man',
    universe: 'Chainsaw Man',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'Smash',
    difficulty: 'Very Hard',
    titleFr: 'Chainsaw Man',
    stage: 'Tokyo Public Safety Devil Hunt',
    boss: 'Gun Devil Catastrophe',
    hero: ['denji_chainsaw', 'Denji', 'slayer'],
    allies: [['power_blood_fiend', 'Power', 'horror'], ['aki_hayakawa', 'Aki Hayakawa', 'tactical']],
    monsters: ['Bat Devil', 'Eternity Devil', 'Zombie Devil Horde'],
    bosses: ['Katana Man', 'Bomb Devil Reze'],
    gear: [['pochita_pull_cord', 'Pochita Pull Cord', 'Cordon de Pochita', { atk: 10, hp: 40 }], ['fox_contract_seal', 'Fox Devil Contract Seal', 'Sceau du Demon-Renard', { atk: 8, spd: 2 }], ['aki_curse_nail', 'Aki Curse Nail', 'Clou maudit d Aki', { atk: 12, def: 3 }]],
    event: ['evt_chainsaw_transformation', 'Chainsaw Transformation', 'Transformation tronconneuse', 'Denji pulls the cord, tears through the hostile line, and restores health by drinking devil blood.', 'Denji tire sur le cordon, dechire la ligne hostile et recupere de la vie avec le sang des demons.'],
    theme: 'Public Safety devil contracts, chainsaw transformations, fiends, and lethal bargains in Tokyo',
    desc: { en: 'Public Safety hunters survive by contracting devils whose prices remain binding inside the Breach.', fr: 'Les chasseurs de la Securite publique survivent grace a des contrats demoniaques dont le prix reste valable dans la Breche.' },
    motif: 'arcanecity',
    colors: ['#241413', '#050202', '#ff3b24'],
    stageVariants: [['Tactics', 'Hotel Eternity Devil Loop', 'Very Hard', 'Eternity Devil'], ['RPG', 'Gun Devil Snowfield Memory', 'Expert', 'Gun Devil Catastrophe']]
  },
  {
    key: 'cyberpunk_edgerunners',
    universe: 'Cyberpunk: Edgerunners',
    mediaType: 'series',
    faction: 'cyber',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Cyberpunk: Edgerunners',
    stage: 'Night City Arasaka Tower Run',
    boss: 'Adam Smasher Full Borg',
    hero: ['david_martinez', 'David Martinez', 'slayer'],
    allies: [['lucy_edgerunners', 'Lucy', 'hacker'], ['rebecca_edgerunners', 'Rebecca', 'marine']],
    monsters: ['Maelstrom Borg', 'Arasaka Security Trooper', 'Militech Combat Drone'],
    bosses: ['Maine Cyberpsychosis', 'Militech Basilisk Convoy'],
    gear: [['david_sandevistan', 'Military Sandevistan', 'Sandevistan militaire', { spd: 3, atk: 8 }], ['lucy_monowire', 'Lucy Monowire', 'Monofilament de Lucy', { atk: 10, spd: 2 }], ['rebecca_guts', 'Rebeccas Guts Shotgun', 'Fusil Guts de Rebecca', { atk: 12, hp: 35 }]],
    event: ['evt_edgerunner_overclock', 'Sandevistan Overclock', 'Sandevistan en surcharge', 'David chains impossible movements before cyberpsychosis pressure catches up with him.', 'David enchaine des mouvements impossibles avant que la pression cyberpsychotique ne le rattrape.'],
    theme: 'Night City mercenary runs, chrome overload, netrunning, and cyberpsychosis under Arasaka pressure',
    desc: { en: 'Edgerunners trade flesh, time, and sanity for one more job beneath Arasakas control of Night City.', fr: 'Les edgerunners echangent chair, temps et raison contre une mission de plus sous le controle d Arasaka sur Night City.' },
    motif: 'arcanecity',
    colors: ['#18162c', '#030306', '#f5e942'],
    stageVariants: [['Smash', 'Santo Domingo Highway Ambush', 'Hard', 'Militech Basilisk Convoy'], ['RPG', 'Moon Dream Braindance', 'Very Hard', 'Adam Smasher Full Borg']]
  },
  {
    key: 'demon_slayer',
    universe: 'Demon Slayer',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'Smash',
    difficulty: 'Very Hard',
    titleFr: 'Demon Slayer',
    stage: 'Infinity Castle Demon Hunt',
    boss: 'Muzan Kibutsuji',
    hero: ['tanjiro_kamado', 'Tanjiro Kamado', 'slayer'],
    allies: [['nezuko_kamado', 'Nezuko Kamado', 'horror'], ['zenitsu_agatsuma', 'Zenitsu Agatsuma', 'slayer']],
    monsters: ['Hand Demon', 'Swamp Demon', 'Spider Demon Family'],
    bosses: ['Akaza Upper Three', 'Daki and Gyutaro'],
    gear: [['tanjiro_nichirin', 'Black Nichirin Blade', 'Lame Nichirin noire', { atk: 11, spd: 1 }], ['hanafuda_earrings', 'Hanafuda Earrings', 'Boucles Hanafuda', { atk: 7, def: 5 }], ['wisteria_poison', 'Wisteria Poison', 'Poison de glycine', { atk: 9, spd: 2 }]],
    event: ['evt_hinokami_kagura', 'Hinokami Kagura', 'Danse du Dieu du Feu', 'Tanjiro converts remembered dance forms into a continuous solar-breathing assault.', 'Tanjiro transforme les formes de la danse transmise en assaut continu du Souffle du Soleil.'],
    theme: 'Taisho-era demon hunts, breathing forms, Blood Demon Arts, and the bonds of the Kamado family',
    desc: { en: 'Nichirin steel and breathing disciplines remain the only reliable answer to Muzans demon blood.', fr: 'L acier Nichirin et les souffles restent la seule reponse fiable au sang demoniaque de Muzan.' },
    motif: 'castle',
    colors: ['#172520', '#030504', '#e54838'],
    stageVariants: [['RPG', 'Mount Natagumo Web Forest', 'Hard', 'Spider Demon Family'], ['Tactics', 'Entertainment District Rooftops', 'Very Hard', 'Daki and Gyutaro']]
  },
  {
    key: 'parasyte',
    universe: 'Parasyte',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'RPG',
    difficulty: 'Very Hard',
    titleFr: 'Parasyte',
    stage: 'East Fukuyama Parasite Hunt',
    boss: 'Gotou Five-Parasite Body',
    hero: ['shinichi_migi', 'Shinichi Izumi and Migi', 'horror'],
    allies: [['satomi_murano', 'Satomi Murano', 'tactical'], ['mamoru_uda', 'Mamoru Uda and Jaw', 'slayer']],
    monsters: ['Split-Head Parasite', 'Parasite Dog', 'City Hall Parasite Host'],
    bosses: ['Reiko Tamura', 'Hideo Shimada'],
    gear: [['migi_cell_sample', 'Migi Cell Sample', 'Echantillon cellulaire de Migi', { hp: 70, spd: 2 }], ['parasite_blade_arm', 'Parasite Blade Arm', 'Bras-lame parasite', { atk: 11 }], ['shinichi_school_bag', 'Shinichis School Bag', 'Sac scolaire de Shinichi', { def: 6, hp: 45 }]],
    event: ['evt_migi_reflex', 'Migi Autonomous Reflex', 'Reflexe autonome de Migi', 'Migi blocks a lethal strike while Shinichi reads the attackers killing intent.', 'Migi bloque un coup mortel pendant que Shinichi lit l intention meurtriere de l attaquant.'],
    theme: 'body-snatching parasites, human empathy, predatory biology, and Shinichis uneasy symbiosis with Migi',
    desc: { en: 'This is Parasyte, not Parasite Eve: alien organisms replace human heads while Migi remains trapped in Shinichis right hand.', fr: 'Il s agit de Parasyte, pas de Parasite Eve: des organismes extraterrestres remplacent les tetes humaines tandis que Migi reste prisonnier de la main droite de Shinichi.' },
    motif: 'facility',
    colors: ['#252118', '#050403', '#d8e36b'],
    stageVariants: [['Tactics', 'Fukuyama City Hall Assault', 'Very Hard', 'Reiko Tamura'], ['Smash', 'Forest Fire Gotou Pursuit', 'Expert', 'Gotou Five-Parasite Body']]
  },
  {
    key: 'steins_gate',
    universe: 'Steins;Gate',
    mediaType: 'series',
    faction: 'cyber',
    mode: 'RPG',
    difficulty: 'Hard',
    titleFr: 'Steins;Gate',
    stage: 'Akihabara Future Gadget Laboratory',
    boss: 'SERN Attractor Field',
    hero: ['rintaro_okabe', 'Rintaro Okabe', 'hacker'],
    allies: [['kurisu_makise', 'Kurisu Makise', 'hacker'], ['itaru_hashida', 'Itaru Hashida', 'tactical']],
    monsters: ['SERN Rounder', 'Jellyman Experiment', 'D-Mail Divergence Echo'],
    bosses: ['FB Rounder Network', 'Nae Time-Leap Echo'],
    gear: [['phonewave', 'PhoneWave Name Subject to Change', 'PhoneWave nom provisoire', { spd: 2, atk: 6 }], ['ibn_5100', 'IBN 5100', 'IBN 5100', { def: 8, hp: 55 }], ['divergence_meter', 'Divergence Meter', 'Divergence Meter', { spd: 2, def: 5 }]],
    event: ['evt_operation_skuld', 'Operation Skuld', 'Operation Skuld', 'Okabe deceives observed history without changing the event the world believes it witnessed.', 'Okabe trompe l histoire observee sans changer l evenement que le monde croit avoir vu.'],
    theme: 'D-Mails, world lines, Reading Steiner, SERN pursuit, and the cost of forcing convergence to change',
    desc: { en: 'Time travel follows world-line convergence rather than free rewinds, and Okabe alone retains memories across shifts.', fr: 'Le voyage temporel suit la convergence des lignes d univers plutot qu un rembobinage libre, et Okabe seul conserve ses souvenirs entre les changements.' },
    motif: 'facility',
    colors: ['#241c16', '#050403', '#ff9a3d'],
    stageVariants: [['Tactics', 'SERN Rounder Apartment Raid', 'Very Hard', 'FB Rounder Network'], ['Smash', 'Radio Kaikan Operation Skuld', 'Expert', 'SERN Attractor Field']]
  },
  {
    key: 'zero_escape_nonary',
    universe: 'Zero Escape: The Nonary Games',
    mediaType: 'game',
    faction: 'cyber',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Zero Escape: The Nonary Games',
    stage: 'Gigantic Nonary Game',
    boss: 'Zero Time-Door Protocol',
    hero: ['junpei_tenmyouji', 'Junpei Tenmyouji', 'tactical'],
    allies: [['akane_kurashiki', 'Akane Kurashiki', 'hacker'], ['sigma_klim', 'Sigma Klim', 'marine']],
    monsters: ['Bracelet Bomb Enforcer', 'Q Room Trap Drone', 'Radical-6 Host'],
    bosses: ['Dio Myrmidon', 'Zero II Decision Engine'],
    gear: [['digital_root_watch', 'Digital Root Bracelet', 'Bracelet a racine numerique', { def: 7, spd: 1 }], ['morphogenetic_key', 'Morphogenetic Key', 'Cle morphogenetique', { atk: 7, spd: 2 }], ['antidote_accelavir', 'Accelavir Dose', 'Dose d Accelavir', { hp: 90 }]],
    event: ['evt_nonary_shift', 'Morphogenetic Shift', 'Transfert morphogenetique', 'A memory from another decision branch reveals the safe door before the timer expires.', 'Un souvenir venu d une autre branche de decision revele la bonne porte avant la fin du chrono.'],
    theme: 'numbered doors, bracelet bombs, escape rooms, morphogenetic memory, and branching decision timelines',
    desc: { en: 'The Nonary Game preserves its arithmetic doors, lethal bracelets, and information transfer across decision branches.', fr: 'Le Nonary Game conserve ses portes arithmetiques, ses bracelets mortels et ses transferts d information entre branches de decision.' },
    motif: 'shipdeck',
    colors: ['#111b25', '#020406', '#52c9ff'],
    stageVariants: [['RPG', 'AB Project Lunar Facility', 'Very Hard', 'Zero II Decision Engine'], ['Smash', 'Decision Game Underground Ward', 'Expert', 'Zero Time-Door Protocol']]
  },
  {
    key: 'jojo_bizarre_adventure',
    universe: "JoJo's Bizarre Adventure",
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'Smash',
    difficulty: 'Very Hard',
    titleFr: 'JoJos Bizarre Adventure',
    stage: 'Cairo DIO Mansion Pursuit',
    boss: 'DIO The World',
    hero: ['jotaro_kujo', 'Jotaro Kujo', 'slayer'],
    allies: [['joseph_joestar', 'Joseph Joestar', 'tactical'], ['giorno_giovanna', 'Giorno Giovanna', 'hacker']],
    monsters: ['Vampire Zombie', 'Stand User Assassin', 'Pillar Man Spawn'],
    bosses: ['Kars Ultimate Life Form', 'Diavolo King Crimson'],
    gear: [['stand_arrow', 'Stand Arrow', 'Fleche de Stand', { atk: 10, spd: 1 }], ['stone_mask_jojo', 'Stone Mask', 'Masque de pierre', { hp: 65, atk: 7 }], ['red_stone_aja', 'Red Stone of Aja', 'Pierre rouge d Aja', { atk: 8, def: 6 }]],
    event: ['evt_star_platinum_time_stop', 'Star Platinum: The World', 'Star Platinum: The World', 'Jotaro stops time for a brief decisive barrage without granting the squad unrestricted time travel.', 'Jotaro arrete brievement le temps pour une rafale decisive sans offrir a l escouade un voyage temporel libre.'],
    theme: 'Joestar bloodlines, Hamon, Stands, vampires, and flamboyant battles of precise supernatural rules',
    desc: { en: 'Every Stand retains its own range and rule; the Breach cannot turn them into interchangeable magic.', fr: 'Chaque Stand conserve sa portee et sa regle; la Breche ne peut pas les transformer en magie interchangeable.' },
    motif: 'arcanecity',
    colors: ['#241438', '#050208', '#d75cff'],
    stageVariants: [['RPG', 'Battle Tendency Volcano', 'Hard', 'Kars Ultimate Life Form'], ['Tactics', 'Rome Colosseum Requiem', 'Expert', 'Diavolo King Crimson']]
  },
  {
    key: 'rurouni_kenshin',
    universe: 'Rurouni Kenshin',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'RPG',
    difficulty: 'Hard',
    titleFr: 'Kenshin le vagabond',
    stage: 'Kyoto Juppongatana Pursuit',
    boss: 'Makoto Shishio Final Duel',
    hero: ['kenshin_himura', 'Kenshin Himura', 'slayer'],
    allies: [['kaoru_kamiya', 'Kaoru Kamiya', 'tactical'], ['sanosuke_sagara', 'Sanosuke Sagara', 'marine']],
    monsters: ['Juppongatana Swordsman', 'Oniwabanshu Shinobi', 'Gatling Gun Guard'],
    bosses: ['Aoshi Shinomori', 'Soujiro Seta'],
    gear: [['sakabato', 'Sakabato Reverse-Blade Sword', 'Sabre a lame inversee', { atk: 9, def: 6 }], ['zanbato_fragment', 'Zanbato Fragment', 'Fragment de Zanbato', { atk: 11, hp: 35 }], ['kamiya_scroll', 'Kamiya Kasshin Scroll', 'Rouleau Kamiya Kasshin', { def: 7, spd: 1 }]],
    event: ['evt_amakakeru', 'Amakakeru Ryu no Hirameki', 'Amakakeru Ryu no Hirameki', 'Kenshin commits to one non-lethal Hiten Mitsurugi counter that breaks the attackers stance.', 'Kenshin engage une contre-attaque Hiten Mitsurugi non lethale qui brise la garde adverse.'],
    theme: 'Meiji-era sword schools, Kenshins vow not to kill, revolution scars, and the Kyoto conspiracy',
    desc: { en: 'Kenshins reverse-blade vow remains a gameplay constraint, not cosmetic flavor.', fr: 'Le serment de Kenshin et sa lame inversee restent une contrainte de gameplay, pas un simple detail cosmetique.' },
    motif: 'castle',
    colors: ['#351716', '#060202', '#e6c05c'],
    stageVariants: [['Tactics', 'Kamiya Dojo Defense', 'Medium', 'Aoshi Shinomori'], ['Smash', 'Shishio Burning Ironclad', 'Very Hard', 'Makoto Shishio Final Duel']]
  },
  {
    key: 'tokyo_ghoul',
    universe: 'Tokyo Ghoul',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'RPG',
    difficulty: 'Very Hard',
    titleFr: 'Tokyo Ghoul',
    stage: 'Ward 20 Anteiku Siege',
    boss: 'One-Eyed Owl',
    hero: ['ken_kaneki', 'Ken Kaneki', 'horror'],
    allies: [['touka_kirishima', 'Touka Kirishima', 'slayer'], ['koutarou_amon', 'Koutarou Amon', 'tactical']],
    monsters: ['Aogiri Ghoul', 'CCG Quinque Investigator', 'Kagune Predator'],
    bosses: ['Yamori Jason', 'Eto Owl'],
    gear: [['kaneki_mask', 'Kanekis Ghoul Mask', 'Masque de Kaneki', { atk: 8, def: 5 }], ['quinque_case', 'Quinque Case', 'Mallette Quinque', { atk: 10, def: 3 }], ['anteiku_coffee', 'Anteiku Coffee', 'Cafe de l Anteiku', { hp: 85 }]],
    event: ['evt_kakuja_break', 'Kakuja Break', 'Rupture Kakuja', 'Kaneki releases a controlled kagune burst at the cost of hunger and stability.', 'Kaneki libere une poussee controlee de kagune au prix de sa faim et de sa stabilite.'],
    theme: 'ghoul hunger, kagune biology, CCG investigations, and Kanekis fractured human identity',
    desc: { en: 'Ghouls cannot live on ordinary food, and every use of kagune reinforces the moral pressure between Anteiku and the CCG.', fr: 'Les goules ne peuvent pas vivre de nourriture ordinaire, et chaque kagune renforce la tension morale entre l Anteiku et le CCG.' },
    motif: 'arcanecity',
    colors: ['#16151a', '#030304', '#d92f45'],
    stageVariants: [['Tactics', 'Cochlea Ghoul Prison Break', 'Very Hard', 'Yamori Jason'], ['Smash', 'Tokyo Rooftop Owl Raid', 'Expert', 'One-Eyed Owl']]
  },
  {
    key: 'cowboy_bebop',
    universe: 'Cowboy Bebop',
    mediaType: 'series',
    faction: 'sciFi',
    mode: 'Tactics',
    difficulty: 'Hard',
    titleFr: 'Cowboy Bebop',
    stage: 'Mars Red Dragon Bounty',
    boss: 'Vicious Red Dragon Syndicate',
    hero: ['spike_spiegel', 'Spike Spiegel', 'tactical'],
    allies: [['faye_valentine', 'Faye Valentine', 'slayer'], ['jet_black', 'Jet Black', 'marine']],
    monsters: ['Red Dragon Gunman', 'Space Pirate Bounty', 'ISSP Security Drone'],
    bosses: ['Mad Pierrot Tongpu', 'Asimov Red Eye Berserker'],
    gear: [['spike_jericho', 'Jericho 941 R', 'Jericho 941 R', { atk: 10, spd: 1 }], ['faye_glock', 'Fayes Glock 30', 'Glock 30 de Faye', { atk: 8, spd: 2 }], ['bebop_bounty_file', 'Bebop Bounty File', 'Dossier de prime du Bebop', { def: 5, hp: 60 }]],
    event: ['evt_bebop_bell_peppers', 'Bell Peppers and Beef', 'Poivrons et boeuf', 'Jet patches the crew up with whatever remains in the galley before the next bounty.', 'Jet remet l equipe sur pied avec ce qui reste dans la cuisine avant la prochaine prime.'],
    theme: 'solar-system bounty hunting, jazz timing, old syndicate wounds, and the broke crew of the Bebop',
    desc: { en: 'Bounties, fuel, ammunition, and unresolved pasts matter more than generic space heroics.', fr: 'Les primes, le carburant, les munitions et les passifs non resolus comptent plus qu un heroisme spatial generique.' },
    motif: 'shipdeck',
    colors: ['#16232b', '#030506', '#e6bc4f'],
    stageVariants: [['RPG', 'Bebop Hangar Bounty Briefing', 'Medium', 'Asimov Red Eye Berserker'], ['Smash', 'Mars Cathedral Ballad', 'Very Hard', 'Vicious Red Dragon Syndicate']]
  },
  {
    key: 'dragon_ball_z',
    universe: 'Dragon Ball Z',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'Smash',
    difficulty: 'Expert',
    titleFr: 'Dragon Ball Z',
    stage: 'Cell Games Arena',
    boss: 'Majin Buu Planetary Crisis',
    hero: ['goku_dbz', 'Son Goku', 'slayer'],
    allies: [['vegeta_dbz', 'Vegeta', 'slayer'], ['piccolo_dbz', 'Piccolo', 'tactical']],
    monsters: ['Saibaman', 'Frieza Soldier', 'Cell Junior'],
    bosses: ['Frieza Final Form', 'Perfect Cell'],
    gear: [['senzu_bean', 'Senzu Bean', 'Haricot Senzu', { hp: 120 }], ['scouter_dbz', 'Saiyan Scouter', 'Detecteur Saiyan', { atk: 6, spd: 2 }], ['dragon_radar', 'Dragon Radar', 'Radar du Dragon', { def: 6, spd: 2 }]],
    event: ['evt_spirit_bomb', 'Spirit Bomb', 'Genkidama', 'Allied life energy gathers slowly into a single attack whose charge must be protected.', 'L energie vitale des allies se rassemble lentement en une attaque unique dont la charge doit etre protegee.'],
    theme: 'Saiyan transformations, ki control, Namek, androids, Cell, and the escalating Majin Buu crisis',
    desc: { en: 'Power rises through training, ki discipline, and defined transformations rather than free Nexus scaling.', fr: 'La puissance progresse par entrainement, maitrise du ki et transformations definies, pas par une inflation libre du Nexus.' },
    motif: 'wasteland',
    colors: ['#132c47', '#020609', '#ff9d28'],
    stageVariants: [['Tactics', 'Namek Frieza Landing Zone', 'Very Hard', 'Frieza Final Form'], ['RPG', 'Hyperbolic Time Chamber', 'Expert', 'Perfect Cell']]
  },
  {
    key: 'elfen_lied',
    universe: 'Elfen Lied',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'RPG',
    difficulty: 'Very Hard',
    titleFr: 'Elfen Lied',
    stage: 'Kamakura Diclonius Facility Escape',
    boss: 'Lucy Vector Catastrophe',
    hero: ['lucy_nyu', 'Lucy and Nyu', 'horror'],
    allies: [['nana_diclonius', 'Nana', 'slayer'], ['kouta_elfen', 'Kouta', 'tactical']],
    monsters: ['SAT Containment Trooper', 'Diclonius Silpelit', 'Research Facility Guard'],
    bosses: ['Mariko Number 35', 'Chief Kakuzawa Diclonius'],
    gear: [['diclonius_horn_fragment', 'Diclonius Horn Fragment', 'Fragment de corne Diclonius', { atk: 10, hp: 35 }], ['music_box_elfen', 'Koutas Music Box', 'Boite a musique de Kouta', { hp: 70, def: 5 }], ['containment_collar', 'Vector Containment Collar', 'Collier de confinement vectoriel', { def: 8 }]],
    event: ['evt_vector_field', 'Invisible Vector Field', 'Champ de vecteurs invisibles', 'Lucy projects invisible arms through cover while trauma destabilizes her control.', 'Lucy projette ses bras invisibles a travers la couverture tandis que son trauma fragilise son controle.'],
    theme: 'Diclonius vectors, laboratory abuse, fractured identity, and the fragile found family at Kaede House',
    desc: { en: 'Invisible vectors keep their limited reach and lethal force; Nyu and Lucy remain parts of one traumatized identity.', fr: 'Les vecteurs invisibles gardent leur portee limitee et leur force mortelle; Nyu et Lucy restent les facettes d une meme identite traumatisee.' },
    motif: 'facility',
    colors: ['#2a1420', '#050203', '#ff6e9d'],
    stageVariants: [['Tactics', 'Kaede House Coastal Defense', 'Hard', 'Mariko Number 35'], ['Smash', 'Research Island Vector Storm', 'Expert', 'Lucy Vector Catastrophe']]
  },
  {
    key: 'fullmetal_alchemist',
    universe: 'Fullmetal Alchemist',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Fullmetal Alchemist',
    stage: 'Central Promised Day',
    boss: 'Father Beyond the Gate',
    hero: ['edward_elric', 'Edward Elric', 'hacker'],
    allies: [['alphonse_elric', 'Alphonse Elric', 'marine'], ['roy_mustang', 'Roy Mustang', 'tactical']],
    monsters: ['Mannequin Soldier', 'State Alchemist Chimera', 'Central Command Trooper'],
    bosses: ['Pride Selim Bradley', 'King Bradley Wrath'],
    gear: [['state_alchemist_watch', 'State Alchemist Pocket Watch', 'Montre d Alchimiste d Etat', { def: 6, spd: 2 }], ['philosophers_stone_shard', 'Philosophers Stone Shard', 'Eclat de Pierre philosophale', { atk: 10, hp: 50 }], ['flame_glove', 'Mustangs Ignition Glove', 'Gant d ignition de Mustang', { atk: 11 }]],
    event: ['evt_equivalent_exchange', 'Equivalent Exchange Array', 'Cercle d echange equivalent', 'The Elrics rebuild cover from available matter without creating material from nothing.', 'Les Elric reconstruisent une couverture avec la matiere disponible sans rien creer a partir du neant.'],
    theme: 'equivalent exchange, human transmutation, homunculi, Amestris conspiracies, and the Promised Day',
    desc: { en: 'Alchemy obeys equivalent exchange and transmutation circles unless a Gate-trained alchemist pays the proper price.', fr: 'L alchimie obeit a l echange equivalent et aux cercles de transmutation, sauf si un alchimiste passe par la Porte et paie le prix.' },
    motif: 'fortress',
    colors: ['#1f2b31', '#040607', '#d7b65a'],
    stageVariants: [['RPG', 'Laboratory Five Homunculus Trap', 'Hard', 'Pride Selim Bradley'], ['Smash', 'Briggs Fortress Invasion', 'Very Hard', 'King Bradley Wrath']]
  },
  {
    key: 'gantz',
    universe: 'Gantz',
    mediaType: 'manga',
    faction: 'sciFi',
    mode: 'Tactics',
    difficulty: 'Expert',
    titleFr: 'Gantz',
    stage: 'Tokyo Gantz Room Mission',
    boss: 'Nurarihyon Osaka Final Form',
    hero: ['kei_kurono', 'Kei Kurono', 'slayer'],
    allies: [['masaru_kato', 'Masaru Kato', 'tactical'], ['reika_shimohira', 'Reika Shimohira', 'marine']],
    monsters: ['Onion Alien', 'Tanaka Alien', 'Buddhist Statue Alien'],
    bosses: ['Nura Alien Tengu', 'Italian Statue God'],
    gear: [['gantz_x_gun', 'Gantz X-Gun', 'X-Gun de Gantz', { atk: 11, spd: 1 }], ['gantz_suit', 'Gantz Reinforcement Suit', 'Combinaison renforcee Gantz', { def: 9, hp: 65 }], ['gantz_y_gun', 'Gantz Y-Gun', 'Y-Gun de Gantz', { atk: 8, def: 5 }]],
    event: ['evt_gantz_transfer', 'Gantz Transfer Recall', 'Rappel de transfert Gantz', 'The black sphere recalls surviving hunters before the mission boundary erases them.', 'La sphere noire rappelle les chasseurs survivants avant que la limite de mission ne les efface.'],
    theme: 'dead recruits, timed alien hunts, opaque scoring, black-sphere technology, and disposable survival missions',
    desc: { en: 'Gantz controls equipment, mission boundaries, scoring, and revival; A.R.C.A. cannot simply free its hunters.', fr: 'Gantz controle equipement, limites de mission, score et resurrection; A.R.C.A. ne peut pas simplement liberer ses chasseurs.' },
    motif: 'arcanecity',
    colors: ['#111214', '#020203', '#4fcfff'],
    stageVariants: [['Smash', 'Osaka Team Nurarihyon Hunt', 'Expert', 'Nurarihyon Osaka Final Form'], ['RPG', 'Rome Statue Massacre', 'Expert', 'Italian Statue God']]
  },
  {
    key: 'psycho_pass',
    universe: 'Psycho-Pass',
    mediaType: 'series',
    faction: 'cyber',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Psycho-Pass',
    stage: 'Tokyo Public Safety Bureau Sweep',
    boss: 'Sibyl System Collective',
    hero: ['akane_tsunemori', 'Akane Tsunemori', 'tactical'],
    allies: [['shinya_kogami', 'Shinya Kogami', 'marine'], ['nobuchika_ginoza', 'Nobuchika Ginoza', 'tactical']],
    monsters: ['Helmet Rioter', 'Crime Coefficient Drone', 'Sibyl Security Enforcer'],
    bosses: ['Shogo Makishima', 'Kirito Kamui'],
    gear: [['dominator_psychopass', 'Dominator', 'Dominator', { atk: 10, def: 4 }], ['holo_disguise', 'Holographic Disguise', 'Deguisement holographique', { spd: 2, def: 6 }], ['cymatic_scan', 'Cymatic Scan Lens', 'Lentille de scan cymatique', { def: 7, hp: 45 }]],
    event: ['evt_dominator_mode', 'Dominator Mode Authorization', 'Autorisation du Dominator', 'Sibyl measures the target and authorizes only the mode allowed by its current Crime Coefficient.', 'Sibyl mesure la cible et n autorise que le mode permis par son Coefficient de Criminalite.' ],
    theme: 'Crime Coefficients, Dominator authorization, Inspectors, Enforcers, and the moral machinery of Sibyl',
    desc: { en: 'The Dominator never becomes a generic gun: its target scan and Sibyl authorization gate every shot.', fr: 'Le Dominator ne devient jamais une arme generique: scan de cible et autorisation de Sibyl conditionnent chaque tir.' },
    motif: 'facility',
    colors: ['#12212c', '#020405', '#52e5ff'],
    stageVariants: [['RPG', 'Hyper-Oats Facility Hostage Route', 'Hard', 'Shogo Makishima'], ['Smash', 'SEAUn Intervention Grid', 'Expert', 'Sibyl System Collective']]
  },
  {
    key: 'mashle',
    universe: 'Mashle',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'Smash',
    difficulty: 'Hard',
    titleFr: 'Mashle',
    stage: 'Easton Magic Academy Trial',
    boss: 'Innocent Zero Timez',
    hero: ['mash_burnedead', 'Mash Burnedead', 'slayer'],
    allies: [['finn_ames', 'Finn Ames', 'tactical'], ['lance_crown', 'Lance Crown', 'hacker']],
    monsters: ['Magia Lupus Student', 'Easton Magic Beast', 'Innocent Zero Doll'],
    bosses: ['Cell War', 'Doom First Son'],
    gear: [['mash_cream_puff', 'Mash Cream Puff', 'Chou a la creme de Mash', { hp: 95 }], ['iron_wand_mashle', 'Mashs Iron Wand', 'Baguette de fer de Mash', { atk: 11, def: 4 }], ['divine_visionary_coin', 'Divine Visionary Coin', 'Piece de l Elu divin', { def: 7, spd: 1 }]],
    event: ['evt_muscle_magic', 'Muscle Magic Full Power', 'Magie musculaire pleine puissance', 'Mash answers a spell with impossible physical force while still possessing no magic at all.', 'Mash repond a un sort par une force physique impossible sans posseder la moindre magie.' ],
    theme: 'a magic academy ruled by marks where Mash survives every spell through absurd physical training',
    desc: { en: 'Mash has no magic and must solve magical threats with strength, timing, and improvised physical technique.', fr: 'Mash ne possede aucune magie et resout les menaces magiques par force, timing et techniques physiques improvisees.' },
    motif: 'castle',
    colors: ['#172c29', '#030605', '#f0d56b'],
    stageVariants: [['RPG', 'Magia Lupus Underground Maze', 'Hard', 'Cell War'], ['Tactics', 'Divine Visionary Selection Arena', 'Very Hard', 'Doom First Son']]
  },
  {
    key: 'solo_leveling',
    universe: 'Solo Leveling',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'RPG',
    difficulty: 'Expert',
    titleFr: 'Solo Leveling',
    stage: 'Cartenon Double Dungeon',
    boss: 'Antares Monarch of Destruction',
    hero: ['sung_jinwoo', 'Sung Jinwoo', 'slayer'],
    allies: [['cha_haein', 'Cha Hae-In', 'slayer'], ['yoo_jinho', 'Yoo Jinho', 'tactical']],
    monsters: ['Dungeon Goblin', 'High Orc Warrior', 'Ice Elf Archer'],
    bosses: ['Blood-Red Commander Igris', 'Ant King Beru'],
    gear: [['kasaka_dagger', 'Kasakas Venom Fang', 'Croc empoisonne de Kasaka', { atk: 10, spd: 2 }], ['demon_king_sword', 'Demon Kings Longsword', 'Epee longue du Roi-Demon', { atk: 12, def: 3 }], ['shadow_extract_rune', 'Shadow Extraction Rune', 'Rune d extraction des ombres', { hp: 60, atk: 7 }]],
    event: ['evt_arise_shadow', 'Arise: Shadow Extraction', 'Leve-toi: extraction d ombre', 'Jinwoo converts a defeated eligible enemy into a temporary named shadow soldier.', 'Jinwoo transforme un ennemi vaincu et compatible en soldat d ombre temporaire et nomme.' ],
    theme: 'hunter gates, the System, daily quests, shadow extraction, Monarchs, and Jinwoos unique leveling path',
    desc: { en: 'Only Jinwoo owns the System and its leveling interface; other hunters retain fixed awakened ranks.', fr: 'Seul Jinwoo possede le Systeme et son interface de niveau; les autres chasseurs gardent leur rang eveille fixe.' },
    motif: 'castle',
    colors: ['#151025', '#030205', '#8b5cff'],
    stageVariants: [['Tactics', 'Jeju Island Ant Nest', 'Very Hard', 'Ant King Beru'], ['Smash', 'Seoul Monarch Invasion', 'Expert', 'Antares Monarch of Destruction']]
  },
  {
    key: 'frieren',
    universe: 'Frieren: Beyond Journeys End',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'RPG',
    difficulty: 'Hard',
    titleFr: 'Frieren',
    stage: 'Northern Plateau Journey',
    boss: 'Demon King Memory',
    hero: ['frieren_elf', 'Frieren', 'hacker'],
    allies: [['fern_mage', 'Fern', 'tactical'], ['stark_warrior', 'Stark', 'marine']],
    monsters: ['Dungeon Mimic', 'Demon Mage', 'Northern Plateau Monster'],
    bosses: ['Aura the Guillotine', 'Macht of El Dorado'],
    gear: [['frieren_grimoire', 'Frierens Collected Grimoire', 'Grimoire collectionne de Frieren', { atk: 9, def: 5 }], ['fern_staff', 'Ferns Staff', 'Baton de Fern', { atk: 10, spd: 1 }], ['stark_axe', 'Starks Great Axe', 'Grande hache de Stark', { atk: 11, hp: 45 }]],
    event: ['evt_zoltraak', 'Zoltraak Barrage', 'Barrage de Zoltraak', 'Frieren and Fern use ordinary modern magic with exceptional concealment, timing, and efficiency.', 'Frieren et Fern emploient une magie moderne ordinaire avec une dissimulation, un timing et une efficacite exceptionnels.' ],
    theme: 'post-quest remembrance, patient magic study, demon deception, and the long northern road to Aureole',
    desc: { en: 'The journey measures decades, memories, mana concealment, and small spells rather than constant escalation.', fr: 'Le voyage se mesure en decennies, souvenirs, dissimulation de mana et petits sorts plutot qu en escalade constante.' },
    motif: 'wasteland',
    colors: ['#24324a', '#05070a', '#bfa6ff'],
    stageVariants: [['Tactics', 'First-Class Mage Exam Ruins', 'Hard', 'Aura the Guillotine'], ['Smash', 'El Dorado Golden Domain', 'Very Hard', 'Macht of El Dorado']]
  },
  {
    key: 'deadman_wonderland',
    universe: 'Deadman Wonderland',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Deadman Wonderland',
    stage: 'G Ward Carnival Corpse',
    boss: 'Wretched Egg Red Hole',
    hero: ['ganta_igarashi', 'Ganta Igarashi', 'tactical'],
    allies: [['shiro_deadman', 'Shiro', 'slayer'], ['senji_kiyomasa', 'Senji Kiyomasa Crow', 'marine']],
    monsters: ['Undertaker Guard', 'Forgeries Deadman', 'Prison Security Drone'],
    bosses: ['Genkaku Azuma', 'Toto Sakigami Mockingbird'],
    gear: [['deadman_collar_candy', 'Deadman Collar Candy', 'Bonbon de collier Deadman', { hp: 85 }], ['ganta_gun_blood', 'Ganta Gun Blood Core', 'Noyau sanguin Ganta Gun', { atk: 10, hp: 35 }], ['crow_blood_blade', 'Crows Blood Blade', 'Lame de sang de Crow', { atk: 11, def: 3 }]],
    event: ['evt_branch_of_sin', 'Branch of Sin Release', 'Liberation de la Branche du Peche', 'Deadmen spend their own blood to form distinct weapons while poison timers keep advancing.', 'Les Deadmen depensent leur propre sang pour former des armes distinctes tandis que le poison des colliers continue.' ],
    theme: 'a privatized prison carnival, poison collars, Branches of Sin, and the hidden G Ward experiments',
    desc: { en: 'Blood weapons cost health and each Deadman retains a specific Branch of Sin instead of generic hemomancy.', fr: 'Les armes de sang coutent de la vie et chaque Deadman conserve sa Branche du Peche au lieu d une hemomancie generique.' },
    motif: 'facility',
    colors: ['#24141a', '#050203', '#ff3d61'],
    stageVariants: [['Smash', 'Dog Race Show Arena', 'Hard', 'Genkaku Azuma'], ['RPG', 'Mother Goose System Chamber', 'Expert', 'Wretched Egg Red Hole']]
  },
  {
    key: 'devilman',
    universe: 'Devilman',
    mediaType: 'manga',
    faction: 'horror',
    mode: 'Smash',
    difficulty: 'Expert',
    titleFr: 'Devilman',
    stage: 'Tokyo Demon Apocalypse',
    boss: 'Satan Final War',
    hero: ['akira_fudo', 'Akira Fudo Devilman', 'horror'],
    allies: [['miki_makimura', 'Miki Makimura', 'tactical'], ['miko_kuroda', 'Miko Kuroda', 'slayer']],
    monsters: ['Sabbath Demon', 'Demon Army Harpy', 'Jinmen Shell Host'],
    bosses: ['Sirene and Kaim', 'Xenon Demon General'],
    gear: [['amon_horn', 'Amon Horn Fragment', 'Fragment de corne d Amon', { atk: 11, hp: 40 }], ['devilman_wing_membrane', 'Devilman Wing Membrane', 'Membrane d aile de Devilman', { spd: 2, def: 5 }], ['miki_baton', 'Mikis Relay Baton', 'Baton relais de Miki', { hp: 70, def: 4 }]],
    event: ['evt_devilman_heart', 'Human Heart in a Demon Body', 'Coeur humain dans un corps demon', 'Akira unleashes Amons body while retaining the empathy that defines Devilman.', 'Akira libere le corps d Amon tout en conservant l empathie qui definit Devilman.' ],
    theme: 'demonic possession, mass paranoia, Akiras human heart, and the apocalyptic war between Satan and humanity',
    desc: { en: 'Akira is powerful because a human heart controls Amons body; losing that empathy would erase the character, not upgrade him.', fr: 'Akira est puissant parce qu un coeur humain controle le corps d Amon; perdre cette empathie effacerait le personnage au lieu de l ameliorer.' },
    motif: 'wasteland',
    colors: ['#1e1014', '#040203', '#e53636'],
    stageVariants: [['RPG', 'Sabbath Club Possession', 'Very Hard', 'Sirene and Kaim'], ['Tactics', 'Demon Army Armageddon', 'Expert', 'Satan Final War']]
  },
  {
    key: 'evangelion',
    universe: 'Neon Genesis Evangelion',
    mediaType: 'series',
    faction: 'sciFi',
    mode: 'Tactics',
    difficulty: 'Expert',
    titleFr: 'Neon Genesis Evangelion',
    stage: 'Tokyo-3 Geofront Defense',
    boss: 'Lilith Third Impact',
    hero: ['shinji_ikari', 'Shinji Ikari and EVA-01', 'tactical'],
    allies: [['asuka_langley', 'Asuka Langley and EVA-02', 'slayer'], ['rei_ayanami', 'Rei Ayanami and EVA-00', 'hacker']],
    monsters: ['Sachiel Third Angel', 'Ramiel Fifth Angel', 'Zeruel Fourteenth Angel'],
    bosses: ['Tabris Kaworu', 'Mass Production Evangelion'],
    gear: [['progressive_knife', 'Progressive Knife', 'Couteau progressif', { atk: 11, spd: 1 }], ['entry_plug', 'Entry Plug', 'Entry Plug', { hp: 80, def: 5 }], ['at_field_core', 'A.T. Field Core', 'Noyau de champ A.T.', { def: 10 }]],
    event: ['evt_at_field', 'A.T. Field Deployment', 'Deploiement du champ A.T.', 'The Evangelion neutralizes an Angels field while its umbilical power timer continues to fall.', 'L Evangelion neutralise le champ d un Ange tandis que son autonomie ombilicale continue de diminuer.' ],
    theme: 'NERV command, biomechanical Evangelions, Angels, synchronization trauma, and the threat of Instrumentality',
    desc: { en: 'Evangelions are restrained biomechanical beings with pilots, synchronization ratios, power limits, and A.T. Fields.', fr: 'Les Evangelions sont des etres biomecaniques contenus avec pilotes, taux de synchronisation, limites d energie et champs A.T.' },
    motif: 'facility',
    colors: ['#181229', '#030205', '#8ce339'],
    stageVariants: [['Smash', 'Tokyo-3 Ramiel Sniper Operation', 'Expert', 'Ramiel Fifth Angel'], ['RPG', 'Terminal Dogma Instrumentality', 'Expert', 'Lilith Third Impact']]
  },
  {
    key: 'naruto',
    universe: 'Naruto',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'RPG',
    difficulty: 'Hard',
    titleFr: 'Naruto',
    stage: 'Chunin Exams Forest of Death',
    boss: 'Orochimaru Konoha Crush',
    hero: ['naruto_uzumaki_young', 'Naruto Uzumaki', 'slayer'],
    allies: [['sasuke_uchiha_young', 'Sasuke Uchiha', 'slayer'], ['sakura_haruno_young', 'Sakura Haruno', 'tactical']],
    monsters: ['Sound Ninja Genin', 'Giant Forest Leech', 'Orochimaru Test Subject'],
    bosses: ['Gaara Shukaku', 'Kabuto Yakushi Chunin'],
    gear: [['kunai_pouch_naruto', 'Konoha Kunai Pouch', 'Sacoche de kunai de Konoha', { atk: 8, spd: 1 }], ['shadow_clone_scroll', 'Shadow Clone Scroll', 'Rouleau du Multi-clonage', { atk: 7, hp: 50 }], ['soldier_pill', 'Akimichi Soldier Pill', 'Pilule militaire Akimichi', { hp: 85, atk: 5 }]],
    event: ['evt_naruto_shadow_clones', 'Multi Shadow Clone Barrage', 'Barrage de Multi-clonage', 'Naruto spends chakra to fill lanes with fragile physical clones that share his intent.', 'Naruto depense du chakra pour remplir les lignes de clones physiques fragiles qui partagent son intention.' ],
    theme: 'Team 7, chakra control, the Chunin Exams, Sannin conflicts, and Narutos first struggle with the Nine-Tails',
    desc: { en: 'This pack stops before the Shippuden time skip and preserves young Team 7s limited techniques and experience.', fr: 'Ce pack s arrete avant l ellipse de Shippuden et conserve les techniques et l experience limitees de la jeune equipe 7.' },
    motif: 'wasteland',
    colors: ['#162d38', '#030607', '#f58b2a'],
    stageVariants: [['Tactics', 'Konoha Rooftop Gaara Pursuit', 'Hard', 'Gaara Shukaku'], ['Smash', 'Valley of the End First Duel', 'Very Hard', 'Orochimaru Konoha Crush']]
  },
  {
    key: 'naruto_shippuden',
    universe: 'Naruto Shippuden',
    mediaType: 'manga',
    faction: 'arcane',
    mode: 'Tactics',
    difficulty: 'Expert',
    titleFr: 'Naruto Shippuden',
    stage: 'Fourth Shinobi World War',
    boss: 'Kaguya Otsutsuki Dimension Shift',
    hero: ['naruto_six_paths', 'Naruto Uzumaki Shippuden', 'slayer'],
    allies: [['sasuke_rinnegan', 'Sasuke Uchiha Shippuden', 'slayer'], ['kakashi_war', 'Kakashi Hatake', 'tactical']],
    monsters: ['White Zetsu Army', 'Edo Tensei Shinobi', 'Pain Summoning Beast'],
    bosses: ['Pain Six Paths', 'Obito Ten-Tails Jinchuriki'],
    gear: [['rasenshuriken_scroll', 'Rasenshuriken Formula', 'Formule du Rasenshuriken', { atk: 11, spd: 1 }], ['rinnegan_lens', 'Rinnegan Chakra Lens', 'Lentille chakra Rinnegan', { atk: 8, def: 7 }], ['kakashi_flak_vest', 'Kakashis Flak Vest', 'Gilet tactique de Kakashi', { def: 8, hp: 55 }]],
    event: ['evt_six_paths_link', 'Six Paths Chakra Link', 'Lien chakra des Six Chemins', 'Naruto shares chakra cloaks with allies while Sasuke anchors the dimensional exit.', 'Naruto partage des manteaux de chakra avec les allies pendant que Sasuke ancre la sortie dimensionnelle.' ],
    theme: 'Akatsuki hunts, tailed beasts, the Fourth Shinobi War, Six Paths power, and the final Team 7 reunion',
    desc: { en: 'Shippuden remains separate from young Naruto so unlock levels, techniques, and narrative prerequisites cannot collapse together.', fr: 'Shippuden reste separe du jeune Naruto afin que niveaux, techniques et prerequis narratifs ne se confondent pas.' },
    motif: 'wasteland',
    colors: ['#23162d', '#050306', '#ff7c28'],
    stageVariants: [['RPG', 'Amegakure Pain Assault', 'Very Hard', 'Pain Six Paths'], ['Smash', 'Kamui Dimension Obito Duel', 'Expert', 'Obito Ten-Tails Jinchuriki']]
  },
  {
    key: 'boruto',
    universe: 'Boruto: Naruto Next Generations',
    mediaType: 'manga',
    faction: 'cyber',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Boruto',
    stage: 'Konoha Chunin Exams Otsutsuki Raid',
    boss: 'Isshiki Otsutsuki',
    hero: ['boruto_uzumaki', 'Boruto Uzumaki', 'slayer'],
    allies: [['sarada_uchiha', 'Sarada Uchiha', 'tactical'], ['mitsuki_boruto', 'Mitsuki', 'hacker']],
    monsters: ['Scientific Ninja Tool Drone', 'Kara Outer', 'Bandit Shinobi'],
    bosses: ['Momoshiki Otsutsuki', 'Boro Regeneration Core'],
    gear: [['boruto_scientific_gauntlet', 'Scientific Ninja Tool Gauntlet', 'Gantelet scientifique ninja', { atk: 8, spd: 2 }], ['karma_mark_fragment', 'Karma Mark Fragment', 'Fragment de Karma', { atk: 10, hp: 40 }], ['sarada_headband', 'Saradas Konoha Headband', 'Bandeau de Konoha de Sarada', { def: 7, hp: 45 }]],
    event: ['evt_team7_compression', 'New Team 7 Combination', 'Combinaison de la nouvelle equipe 7', 'Boruto, Sarada, and Mitsuki combine Karma pressure, Sharingan analysis, and Sage movement.', 'Boruto, Sarada et Mitsuki combinent pression du Karma, analyse du Sharingan et mouvement ermite.' ],
    theme: 'a modernized Konoha, scientific ninja tools, the new Team 7, Kara, Karma, and Otsutsuki vessels',
    desc: { en: 'This era uses the original Boruto team before the Two Blue Vortex time skip.', fr: 'Cette periode utilise l equipe de Boruto avant l ellipse de Two Blue Vortex.' },
    motif: 'arcanecity',
    colors: ['#182c38', '#030607', '#f34d9a'],
    stageVariants: [['RPG', 'Kara Boro Cult Chamber', 'Very Hard', 'Boro Regeneration Core'], ['Smash', 'Konoha Isshiki Invasion', 'Expert', 'Isshiki Otsutsuki']]
  },
  {
    key: 'boruto_two_blue_vortex',
    universe: 'Boruto: Two Blue Vortex',
    mediaType: 'manga',
    faction: 'cyber',
    mode: 'RPG',
    difficulty: 'Expert',
    titleFr: 'Boruto: Two Blue Vortex',
    stage: 'Time-Skip Konoha Claw Grime Siege',
    boss: 'Jura Divine Tree Incarnation',
    hero: ['boruto_tbv', 'Boruto Uzumaki Two Blue Vortex', 'slayer'],
    allies: [['sarada_tbv', 'Sarada Uchiha Two Blue Vortex', 'tactical'], ['kawaki_tbv', 'Kawaki', 'marine']],
    monsters: ['Claw Grime', 'God Tree Spawn', 'Code Claw Mark Raider'],
    bosses: ['Code Limitless', 'Hidari Divine Tree'],
    gear: [['uzuhiko_formula', 'Rasengan Uzuhiko Formula', 'Formule du Rasengan Uzuhiko', { atk: 12, spd: 1 }], ['sasuke_sword_tbv', 'Sasukes Sword', 'Epee de Sasuke', { atk: 10, def: 4 }], ['omnipotence_memory', 'Omnipotence Memory Anchor', 'Ancre memoire d Omnipotence', { def: 8, hp: 55 }]],
    event: ['evt_uzuhiko', 'Rasengan Uzuhiko', 'Rasengan Uzuhiko', 'Boruto binds planetary rotation to the targets balance until the technique is released.', 'Boruto lie la rotation planetaire a l equilibre de la cible jusqu a la liberation de la technique.' ],
    theme: 'post-Omnipotence identities, Borutos exile, Claw Grimes, evolved Divine Trees, and a changed Konoha',
    desc: { en: 'Two Blue Vortex remains a distinct time-skip universe so its identities, powers, and spoilers do not overwrite early Boruto.', fr: 'Two Blue Vortex reste un univers distinct afin que ses identites, pouvoirs et revelations n ecrasent pas le premier Boruto.' },
    motif: 'arcanecity',
    colors: ['#1b1830', '#030306', '#47c8ff'],
    stageVariants: [['Tactics', 'Code Ten-Tails Pocket Dimension', 'Expert', 'Code Limitless'], ['Smash', 'Divine Tree Konoha Hunt', 'Expert', 'Jura Divine Tree Incarnation']]
  },
  {
    key: 'one_punch_man',
    universe: 'One Punch Man',
    mediaType: 'manga',
    faction: 'sciFi',
    mode: 'Smash',
    difficulty: 'Expert',
    titleFr: 'One Punch Man',
    stage: 'City A Hero Association Assault',
    boss: 'Boros Meteoric Burst',
    hero: ['saitama_opm', 'Saitama', 'slayer'],
    allies: [['genos_opm', 'Genos', 'marine'], ['tatsumaki_opm', 'Tatsumaki', 'hacker']],
    monsters: ['Deep Sea Folk', 'Monster Association Beast', 'Machine God Drone'],
    bosses: ['Garou Cosmic Fear', 'Orochi Monster King'],
    gear: [['saitama_glove', 'Saitamas Hero Glove', 'Gant de heros de Saitama', { atk: 12, def: 3 }], ['genos_core', 'Genos Incineration Core', 'Noyau d incineration de Genos', { atk: 11, hp: 45 }], ['hero_association_badge', 'Hero Association Badge', 'Badge de l Association des Heros', { def: 7, hp: 55 }]],
    event: ['evt_serious_punch', 'Serious Punch Shockwave', 'Onde du Coup serieux', 'Saitama uses only the force required to end the current threat without turning every encounter into an automatic clear.', 'Saitama emploie seulement la force necessaire pour terminer la menace actuelle sans transformer chaque combat en victoire automatique.' ],
    theme: 'Hero Association rankings, disaster levels, monsters, cyborg upgrades, and Saitamas deliberately anticlimactic strength',
    desc: { en: 'Saitamas power is handled as an objective and timing constraint so his canon strength does not erase the game.', fr: 'La puissance de Saitama devient une contrainte d objectif et de timing afin que sa force canonique n efface pas le jeu.' },
    motif: 'arcanecity',
    colors: ['#1e2c35', '#040607', '#f4d52d'],
    stageVariants: [['Tactics', 'Monster Association Underground', 'Very Hard', 'Orochi Monster King'], ['RPG', 'Alien Conqueror Ship Deck', 'Expert', 'Boros Meteoric Burst']]
  },
  {
    key: 'sao_gun_gale',
    universe: 'Sword Art Online: Gun Gale Online',
    mediaType: 'series',
    faction: 'cyber',
    mode: 'Tactics',
    difficulty: 'Very Hard',
    titleFr: 'Sword Art Online - Gun Gale Online',
    stage: 'Gun Gale Online Bullet of Bullets',
    boss: 'Death Gun Sterben',
    hero: ['sinon_ggo', 'Sinon', 'marine'],
    allies: [['kirito_ggo', 'Kirito GGO', 'slayer'], ['llenn_ggo', 'LLENN', 'tactical']],
    monsters: ['BoB Assault Gunner', 'Laughing Coffin Remnant', 'Gun Gale Combat Drone'],
    bosses: ['Behemoth Heavy Gunner', 'Pitohui Berserk Avatar'],
    gear: [['hecate_ii', 'PGM Ultima Ratio Hecate II', 'PGM Hecate II', { atk: 12, spd: 1 }], ['photon_sword_ggo', 'Kiritos Photon Sword', 'Sabre photon de Kirito', { atk: 10, def: 4 }], ['optical_camouflage_ggo', 'GGO Optical Camouflage', 'Camouflage optique GGO', { spd: 2, def: 7 }]],
    event: ['evt_bullet_line_read', 'Bullet Line Prediction', 'Prediction des lignes de tir', 'Sinon reads ballistic warning lines and relocates before the first real round reaches her.', 'Sinon lit les lignes d avertissement balistique et se replace avant l arrivee de la premiere balle reelle.' ],
    theme: 'the firearm VRMMO Gun Gale Online, Bullet Lines, sniper duels, Death Gun, and Squad Jam tactics',
    desc: { en: 'This is the firearm-focused SAO branch: rifles, ballistic prediction, ammunition, and VR avatar movement drive combat.', fr: 'Il s agit de la branche armes a feu de SAO: fusils, prediction balistique, munitions et mouvement des avatars VR dirigent le combat.' },
    motif: 'wasteland',
    colors: ['#1c2025', '#040405', '#e55838'],
    stageVariants: [['Smash', 'GGO Desert BoB Ruins', 'Hard', 'Behemoth Heavy Gunner'], ['RPG', 'Squad Jam Urban Killbox', 'Very Hard', 'Pitohui Berserk Avatar']]
  },
  {
    key: 'sword_art_online',
    universe: 'Sword Art Online',
    mediaType: 'series',
    faction: 'cyber',
    mode: 'RPG',
    difficulty: 'Very Hard',
    titleFr: 'Sword Art Online',
    stage: 'Aincrad Floor 74 Labyrinth',
    boss: 'Heathcliff Kayaba Final Duel',
    hero: ['kirito_sao', 'Kirito', 'slayer'],
    allies: [['asuna_sao', 'Asuna', 'slayer'], ['klein_sao', 'Klein', 'tactical']],
    monsters: ['Ruin Kobold Sentinel', 'Laughing Coffin Player Killer', 'Skull Reaper Limb'],
    bosses: ['Illfang the Kobold Lord', 'The Skull Reaper'],
    gear: [['elucidator_sao', 'Elucidator', 'Elucidator', { atk: 11, def: 3 }], ['lambent_light', 'Lambent Light', 'Lambent Light', { atk: 10, spd: 2 }], ['teleport_crystal', 'Teleport Crystal', 'Cristal de teleportation', { hp: 65, spd: 2 }]],
    event: ['evt_starburst_stream', 'Starburst Stream', 'Starburst Stream', 'Kirito executes the sixteen-hit Dual Blades Sword Skill while allies protect its commitment window.', 'Kirito execute les seize coups du Sword Skill Dual Blades pendant que les allies protegent sa fenetre d engagement.' ],
    theme: 'Aincrad death-game rules, floors, Sword Skills, guild raids, player killers, and Kayabas hidden final condition',
    desc: { en: 'Aincrad remains a sword-based death game with menus, crystals, skill cooldowns, and real death on logout failure.', fr: 'Aincrad reste un death game a l epee avec menus, cristaux, temps de recharge et mort reelle en cas d echec.' },
    motif: 'castle',
    colors: ['#18233c', '#030508', '#6fb9ff'],
    stageVariants: [['Tactics', 'Floor 1 Illfang Raid', 'Hard', 'Illfang the Kobold Lord'], ['Smash', 'Floor 75 Skull Reaper Chamber', 'Expert', 'The Skull Reaper']]
  },
  {
    key: 'saturnin_duck',
    universe: 'Les Aventures de Saturnin',
    mediaType: 'series',
    faction: 'arcane',
    mode: 'RPG',
    difficulty: 'Medium',
    titleFr: 'Les Aventures de Saturnin',
    stage: 'Saturnins Miniature Animal Village',
    boss: 'Foxes Village Caper',
    hero: ['saturnin_duck', 'Saturnin the Duck', 'tactical'],
    allies: [['police_dog_saturnin', 'Police Dog', 'marine'], ['professor_popof', 'Professor Popof', 'hacker']],
    monsters: ['Mischievous Fox', 'Runaway Miniature Car', 'Village Garden Mole'],
    bosses: ['Dame Belette Scheme', 'Foxes Village Caper'],
    gear: [['saturnin_ski_goggles', 'Saturnins Ski Goggles', 'Lunettes de ski de Saturnin', { def: 6, spd: 2 }], ['miniature_car_key', 'Miniature Car Key', 'Cle de voiture miniature', { spd: 2, hp: 45 }], ['popof_toolbox', 'Professor Popofs Toolbox', 'Boite a outils du professeur Popof', { def: 7, hp: 50 }]],
    event: ['evt_saturnin_village_chase', 'Saturnin Village Chase', 'Poursuite au village de Saturnin', 'Saturnin rallies the real-animal village through miniature roads, gardens, and a precisely timed rescue.', 'Saturnin mobilise le village d animaux reels a travers routes miniatures, jardins et sauvetage parfaitement cadence.' ],
    theme: 'Jean Touranes real-animal miniature village, a temperamental yellow duckling, and practical everyday adventures',
    desc: { en: 'Saturnin remains the yellow live-action duckling from the French ORTF series, surrounded by real animals in miniature sets.', fr: 'Saturnin reste le caneton jaune en prises de vues reelles de la serie francaise de l ORTF, entoure de vrais animaux dans des decors miniatures.' },
    motif: 'arcanecity',
    colors: ['#2b3518', '#060803', '#ffd83d'],
    stageVariants: [['Tactics', 'Professor Popofs Workshop', 'Medium', 'Dame Belette Scheme'], ['Smash', 'Saturnin Alpine Ski Run', 'Hard', 'Foxes Village Caper']]
  },
  {
    key: 'magic_jack_youtuber',
    universe: 'MagiC JacK',
    mediaType: 'series',
    faction: 'horror',
    mode: 'RPG',
    difficulty: 'Hard',
    titleFr: 'MagiC JacK',
    stage: 'La Minute Sapiens Tribunal',
    boss: 'Human Lobby Incarnation',
    hero: ['magic_jack_ginolin', 'MagiC JacK', 'horror'],
    allies: [['max_rage_ginolin', 'Max Rage', 'slayer'], ['sapiens_witness', 'Sapiens Witness', 'tactical']],
    monsters: ['Lobby Advocate', 'Consumption Avatar', 'Speciesist Broadcast Drone'],
    bosses: ['Human Lobby Incarnation', 'Polymorph Judgment Double'],
    gear: [['magicjack_judge_hammer', 'MagiC JacK Judges Hammer', 'Marteau de juge MagiC JacK', { atk: 9, def: 5 }], ['sapiens_camera', 'La Minute Sapiens Camera', 'Camera de La Minute Sapiens', { spd: 2, def: 6 }], ['max_rage_microphone', 'Max Rage Microphone', 'Micro de Max Rage', { atk: 8, hp: 50 }]],
    event: ['evt_magicjack_polymorph', 'Alien Polymorph Indictment', 'Requisitoire polymorphe extraterrestre', 'MagiC JacK changes form to expose a human contradiction rather than borrowing an unrelated superpower.', 'MagiC JacK change de forme pour exposer une contradiction humaine sans emprunter un pouvoir etranger.' ],
    theme: 'Maxime Ginolins polymorphic alien persona, courtroom satire, filmmaking, music, and confrontational human critique',
    desc: { en: 'MagiC JacK is the polymorphic alien persona performed by filmmaker and musician Maxime Ginolin, not a generic stage magician.', fr: 'MagiC JacK est le personnage extraterrestre polymorphe interprete par le realisateur et musicien Maxime Ginolin, pas un magicien generique.' },
    motif: 'hauntedset',
    colors: ['#22131d', '#040204', '#f05765'],
    stageVariants: [['Tactics', 'Grosse Social Mirror Set', 'Hard', 'Polymorph Judgment Double'], ['Smash', 'Max Rage Concert Indictment', 'Very Hard', 'Human Lobby Incarnation']]
  },
  {
    key: 'teen_titans',
    universe: 'Teen Titans',
    mediaType: 'series',
    faction: 'arcane',
    mode: 'Smash',
    difficulty: 'Very Hard',
    titleFr: 'Teen Titans',
    stage: 'Titans Tower HIVE Assault',
    boss: 'Trigon Demon Father',
    hero: ['robin_tt', 'Robin', 'tactical'],
    allies: [['cyborg_tt', 'Cyborg', 'marine'], ['raven_tt', 'Raven', 'hacker']],
    monsters: ['H.I.V.E. Five Cadet', 'Control Freak Remote Drone', 'Brother Blood Student'],
    bosses: ['Slade Apprentice Trial', 'Terra Betrayal Golem'],
    worldBoss: 'Trigon Demon Father',
    gear: [['robin_bo_staff', 'Robin Bo Staff', 'Baton de Robin', { atk: 9, spd: 2 }], ['cyborg_sonic_cannon', 'Cyborg Sonic Cannon', 'Canon sonique de Cyborg', { atk: 10, hp: 45 }], ['raven_azarath_cloak', 'Raven Azarath Cloak', 'Cape d Azarath de Raven', { def: 8, hp: 55 }]],
    event: ['evt_titans_go_formation', 'Titans Go Formation', 'Formation Titans Go', 'The team locks one enemy inside Robin tactics, Cyborg pressure, and Raven containment before the breach can isolate them.', 'L equipe verrouille un ennemi entre tactique de Robin, pression de Cyborg et confinement de Raven avant que la breche les isole.'],
    theme: 'Titans Tower teamwork, Slade manipulation, H.I.V.E. pressure, Raven and Trigon prophecy, and teen heroes learning to fight as a unit',
    desc: { en: 'The Titans work as a team first: technology, sorcery, alien strength, animal morphing, and Robin tactics should stay distinct.', fr: 'Les Titans fonctionnent d abord en equipe: technologie, sorcellerie, force extraterrestre, morphing animal et tactique de Robin restent distincts.' },
    motif: 'arcanecity',
    colors: ['#171b2c', '#030306', '#7f5cff'],
    stageVariants: [['Tactics', 'HIVE Academy Break-In', 'Hard', 'Brother Blood Student'], ['RPG', 'Azarath Trigon Eclipse', 'Expert', 'Trigon Demon Father']]
  },
  {
    key: 'godzilla_showa_millennium_legendary',
    universe: 'Godzilla',
    mediaType: 'movie',
    faction: 'sciFi',
    mode: 'Smash',
    difficulty: 'Expert',
    titleFr: 'Godzilla',
    stage: 'Tokyo Kaiju Cataclysm',
    boss: 'Destoroyah Oxygen Destroyer',
    hero: ['godzilla_1954', 'Original Godzilla 1954', 'marine'],
    allies: [['godzilla_millennium', 'Godzilla Millennium', 'slayer'], ['legendary_godzilla', 'Legendary Godzilla', 'marine']],
    monsters: ['JSDF Maser Tank Line', 'MutO Breach Parasite', 'Xilien Control Drone'],
    bosses: ['Shin Godzilla Evolution', 'Biollante Rose Beast'],
    worldBoss: 'Destoroyah Oxygen Destroyer',
    gear: [['oxygen_destroyer_trace', 'Oxygen Destroyer Trace', 'Trace d Oxygen Destroyer', { atk: 12, def: 3 }], ['g_cell_sample', 'G-Cell Sample', 'Echantillon de cellules G', { hp: 95, atk: 5 }], ['maser_battery_pack', 'Maser Battery Pack', 'Batterie Maser', { atk: 8, spd: 2 }]],
    event: ['evt_atomic_breath_chain', 'Atomic Breath Chain', 'Chaine de souffle atomique', 'Godzilla channels one atomic breath line while allies evacuate breach civilians and hold anti-kaiju fire lanes.', 'Godzilla canalise une ligne de souffle atomique pendant que les allies evacuents les civils de breche et tiennent les couloirs anti-kaiju.'],
    theme: 'Godzilla eras kept distinct: 1954 nuclear horror, Millennium aggression, Legendary alpha presence, Shin mutation, Biollante G-cells, and Destoroyah born from the Oxygen Destroyer',
    desc: { en: 'The kaiju roster keeps each continuity as a readable combat identity instead of reducing every Godzilla form to one generic monster.', fr: 'Le roster kaiju garde chaque continuite comme identite de combat lisible au lieu de reduire toutes les formes de Godzilla a un monstre generique.' },
    motif: 'wasteland',
    colors: ['#142126', '#020405', '#63e6ff'],
    stageVariants: [['Tactics', 'Shin Godzilla Evacuation Grid', 'Expert', 'Shin Godzilla Evolution'], ['RPG', 'Biollante Lake Ashinoko Bloom', 'Very Hard', 'Biollante Rose Beast']]
  }
];

REQUESTED_UNIVERSE_WAVE.push(...SOLAR_OPPOSITES_SIREN_STAR_WARS_UNIVERSE_WAVE);
